// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/booking/v1/booking.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HotelId          int64                  `protobuf:"varint,2,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	BookingDateStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=booking_date_start,json=bookingDateStart,proto3" json:"booking_date_start,omitempty"`
	BookingDateEnd   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=booking_date_end,json=bookingDateEnd,proto3" json:"booking_date_end,omitempty"`
	Price            float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Name             string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfGuests   int64                  `protobuf:"varint,7,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_api_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBookingRequest) GetHotelId() int64 {
	if x != nil {
		return x.HotelId
	}
	return 0
}

func (x *CreateBookingRequest) GetBookingDateStart() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingDateStart
	}
	return nil
}

func (x *CreateBookingRequest) GetBookingDateEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingDateEnd
	}
	return nil
}

func (x *CreateBookingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateBookingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBookingRequest) GetNumberOfGuests() int64 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

type CreateBookingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *BookingInfo           `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingReply) Reset() {
	*x = CreateBookingReply{}
	mi := &file_api_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingReply) ProtoMessage() {}

func (x *CreateBookingReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingReply.ProtoReflect.Descriptor instead.
func (*CreateBookingReply) Descriptor() ([]byte, []int) {
	return file_api_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingReply) GetBooking() *BookingInfo {
	if x != nil {
		return x.Booking
	}
	return nil
}

type SeeBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeeBookingsRequest) Reset() {
	*x = SeeBookingsRequest{}
	mi := &file_api_booking_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeeBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeeBookingsRequest) ProtoMessage() {}

func (x *SeeBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeeBookingsRequest.ProtoReflect.Descriptor instead.
func (*SeeBookingsRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *SeeBookingsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SeeBookingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*BookingInfo         `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeeBookingsReply) Reset() {
	*x = SeeBookingsReply{}
	mi := &file_api_booking_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeeBookingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeeBookingsReply) ProtoMessage() {}

func (x *SeeBookingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeeBookingsReply.ProtoReflect.Descriptor instead.
func (*SeeBookingsReply) Descriptor() ([]byte, []int) {
	return file_api_booking_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *SeeBookingsReply) GetBookings() []*BookingInfo {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type BookingInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HotelId          int64                  `protobuf:"varint,3,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BookingDateStart *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=booking_date_start,json=bookingDateStart,proto3" json:"booking_date_start,omitempty"`
	BookingDateEnd   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=booking_date_end,json=bookingDateEnd,proto3" json:"booking_date_end,omitempty"`
	Price            float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	NumberOfGuests   int64                  `protobuf:"varint,8,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BookingInfo) Reset() {
	*x = BookingInfo{}
	mi := &file_api_booking_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingInfo) ProtoMessage() {}

func (x *BookingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingInfo.ProtoReflect.Descriptor instead.
func (*BookingInfo) Descriptor() ([]byte, []int) {
	return file_api_booking_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *BookingInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookingInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BookingInfo) GetHotelId() int64 {
	if x != nil {
		return x.HotelId
	}
	return 0
}

func (x *BookingInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookingInfo) GetBookingDateStart() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingDateStart
	}
	return nil
}

func (x *BookingInfo) GetBookingDateEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingDateEnd
	}
	return nil
}

func (x *BookingInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookingInfo) GetNumberOfGuests() int64 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

func (x *BookingInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BookingInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_booking_v1_booking_proto protoreflect.FileDescriptor

const file_api_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x1capi/booking/v1/booking.proto\x12\x0eapi.booking.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x02\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bhotel_id\x18\x02 \x01(\x03R\ahotelId\x12H\n" +
	"\x12booking_date_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x10bookingDateStart\x12D\n" +
	"\x10booking_date_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ebookingDateEnd\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12(\n" +
	"\x10number_of_guests\x18\a \x01(\x03R\x0enumberOfGuests\"K\n" +
	"\x12CreateBookingReply\x125\n" +
	"\abooking\x18\x01 \x01(\v2\x1b.api.booking.v1.BookingInfoR\abooking\"-\n" +
	"\x12SeeBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"K\n" +
	"\x10SeeBookingsReply\x127\n" +
	"\bbookings\x18\x01 \x03(\v2\x1b.api.booking.v1.BookingInfoR\bbookings\"\xab\x03\n" +
	"\vBookingInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\bhotel_id\x18\x03 \x01(\x03R\ahotelId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12H\n" +
	"\x12booking_date_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10bookingDateStart\x12D\n" +
	"\x10booking_date_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ebookingDateEnd\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12(\n" +
	"\x10number_of_guests\x18\b \x01(\x03R\x0enumberOfGuests\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xe8\x01\n" +
	"\aBooking\x12r\n" +
	"\rCreateBooking\x12$.api.booking.v1.CreateBookingRequest\x1a\".api.booking.v1.CreateBookingReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/bookings\x12i\n" +
	"\vSeeBookings\x12\".api.booking.v1.SeeBookingsRequest\x1a .api.booking.v1.SeeBookingsReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/bookingsB5\n" +
	"\x0eapi.booking.v1P\x01Z!yinni_travel_backend/api/booking/v1;v1b\x06proto3"

var (
	file_api_booking_v1_booking_proto_rawDescOnce sync.Once
	file_api_booking_v1_booking_proto_rawDescData []byte
)

func file_api_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_api_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_api_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_booking_v1_booking_proto_rawDesc), len(file_api_booking_v1_booking_proto_rawDesc)))
	})
	return file_api_booking_v1_booking_proto_rawDescData
}

var file_api_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_booking_v1_booking_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),  // 0: api.booking.v1.CreateBookingRequest
	(*CreateBookingReply)(nil),    // 1: api.booking.v1.CreateBookingReply
	(*SeeBookingsRequest)(nil),    // 2: api.booking.v1.SeeBookingsRequest
	(*SeeBookingsReply)(nil),      // 3: api.booking.v1.SeeBookingsReply
	(*BookingInfo)(nil),           // 4: api.booking.v1.BookingInfo
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_booking_v1_booking_proto_depIdxs = []int32{
	5,  // 0: api.booking.v1.CreateBookingRequest.booking_date_start:type_name -> google.protobuf.Timestamp
	5,  // 1: api.booking.v1.CreateBookingRequest.booking_date_end:type_name -> google.protobuf.Timestamp
	4,  // 2: api.booking.v1.CreateBookingReply.booking:type_name -> api.booking.v1.BookingInfo
	4,  // 3: api.booking.v1.SeeBookingsReply.bookings:type_name -> api.booking.v1.BookingInfo
	5,  // 4: api.booking.v1.BookingInfo.booking_date_start:type_name -> google.protobuf.Timestamp
	5,  // 5: api.booking.v1.BookingInfo.booking_date_end:type_name -> google.protobuf.Timestamp
	5,  // 6: api.booking.v1.BookingInfo.created_at:type_name -> google.protobuf.Timestamp
	5,  // 7: api.booking.v1.BookingInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: api.booking.v1.Booking.CreateBooking:input_type -> api.booking.v1.CreateBookingRequest
	2,  // 9: api.booking.v1.Booking.SeeBookings:input_type -> api.booking.v1.SeeBookingsRequest
	1,  // 10: api.booking.v1.Booking.CreateBooking:output_type -> api.booking.v1.CreateBookingReply
	3,  // 11: api.booking.v1.Booking.SeeBookings:output_type -> api.booking.v1.SeeBookingsReply
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_booking_v1_booking_proto_init() }
func file_api_booking_v1_booking_proto_init() {
	if File_api_booking_v1_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_booking_v1_booking_proto_rawDesc), len(file_api_booking_v1_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_api_booking_v1_booking_proto_depIdxs,
		MessageInfos:      file_api_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_api_booking_v1_booking_proto = out.File
	file_api_booking_v1_booking_proto_goTypes = nil
	file_api_booking_v1_booking_proto_depIdxs = nil
}
