// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/booking/v1/booking.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBookingCreateBooking = "/api.booking.v1.Booking/CreateBooking"
const OperationBookingSeeBookings = "/api.booking.v1.Booking/SeeBookings"

type BookingHTTPServer interface {
	CreateBooking(context.Context, *CreateBookingRequest) (*CreateBookingReply, error)
	SeeBookings(context.Context, *SeeBookingsRequest) (*SeeBookingsReply, error)
}

func RegisterBookingHTTPServer(s *http.Server, srv BookingHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/bookings", _Booking_CreateBooking0_HTTP_Handler(srv))
	r.GET("/v1/bookings", _Booking_SeeBookings0_HTTP_Handler(srv))
}

func _Booking_CreateBooking0_HTTP_Handler(srv BookingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBookingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookingCreateBooking)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBooking(ctx, req.(*CreateBookingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateBookingReply)
		return ctx.Result(200, reply)
	}
}

func _Booking_SeeBookings0_HTTP_Handler(srv BookingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SeeBookingsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookingSeeBookings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SeeBookings(ctx, req.(*SeeBookingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SeeBookingsReply)
		return ctx.Result(200, reply)
	}
}

type BookingHTTPClient interface {
	CreateBooking(ctx context.Context, req *CreateBookingRequest, opts ...http.CallOption) (rsp *CreateBookingReply, err error)
	SeeBookings(ctx context.Context, req *SeeBookingsRequest, opts ...http.CallOption) (rsp *SeeBookingsReply, err error)
}

type BookingHTTPClientImpl struct {
	cc *http.Client
}

func NewBookingHTTPClient(client *http.Client) BookingHTTPClient {
	return &BookingHTTPClientImpl{client}
}

func (c *BookingHTTPClientImpl) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...http.CallOption) (*CreateBookingReply, error) {
	var out CreateBookingReply
	pattern := "/v1/bookings"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBookingCreateBooking))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BookingHTTPClientImpl) SeeBookings(ctx context.Context, in *SeeBookingsRequest, opts ...http.CallOption) (*SeeBookingsReply, error) {
	var out SeeBookingsReply
	pattern := "/v1/bookings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBookingSeeBookings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
