// api/booking/v1/booking_error_reason.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: booking/v1/booking_error_reason.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_BOOKING_UNSPECIFIED       ErrorReason = 0
	ErrorReason_BOOKING_NOT_FOUND         ErrorReason = 1
	ErrorReason_INVALID_BOOKING_ID        ErrorReason = 2
	ErrorReason_INVALID_USER_ID           ErrorReason = 3
	ErrorReason_INVALID_HOTEL_ID          ErrorReason = 4
	ErrorReason_INVALID_BOOKING_DATE      ErrorReason = 5
	ErrorReason_INVALID_PARAMETERS        ErrorReason = 6
	ErrorReason_UNAUTHORIZED              ErrorReason = 7
	ErrorReason_DATABASE_ERROR            ErrorReason = 8
	ErrorReason_BOOKING_ALREADY_CANCELLED ErrorReason = 9
	ErrorReason_BOOKING_CREATION_FAILED   ErrorReason = 10
	// Admin booking errors (9000-9999)
	ErrorReason_BOOKING_JOB_NOT_FOUND       ErrorReason = 9000
	ErrorReason_BOOKING_JOB_ALREADY_RUNNING ErrorReason = 9001
	ErrorReason_BOOKING_JOB_NOT_RUNNING     ErrorReason = 9002
	ErrorReason_BOOKING_JOB_FAILED          ErrorReason = 9003
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:    "BOOKING_UNSPECIFIED",
		1:    "BOOKING_NOT_FOUND",
		2:    "INVALID_BOOKING_ID",
		3:    "INVALID_USER_ID",
		4:    "INVALID_HOTEL_ID",
		5:    "INVALID_BOOKING_DATE",
		6:    "INVALID_PARAMETERS",
		7:    "UNAUTHORIZED",
		8:    "DATABASE_ERROR",
		9:    "BOOKING_ALREADY_CANCELLED",
		10:   "BOOKING_CREATION_FAILED",
		9000: "BOOKING_JOB_NOT_FOUND",
		9001: "BOOKING_JOB_ALREADY_RUNNING",
		9002: "BOOKING_JOB_NOT_RUNNING",
		9003: "BOOKING_JOB_FAILED",
	}
	ErrorReason_value = map[string]int32{
		"BOOKING_UNSPECIFIED":         0,
		"BOOKING_NOT_FOUND":           1,
		"INVALID_BOOKING_ID":          2,
		"INVALID_USER_ID":             3,
		"INVALID_HOTEL_ID":            4,
		"INVALID_BOOKING_DATE":        5,
		"INVALID_PARAMETERS":          6,
		"UNAUTHORIZED":                7,
		"DATABASE_ERROR":              8,
		"BOOKING_ALREADY_CANCELLED":   9,
		"BOOKING_CREATION_FAILED":     10,
		"BOOKING_JOB_NOT_FOUND":       9000,
		"BOOKING_JOB_ALREADY_RUNNING": 9001,
		"BOOKING_JOB_NOT_RUNNING":     9002,
		"BOOKING_JOB_FAILED":          9003,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_booking_v1_booking_error_reason_proto protoreflect.FileDescriptor

const file_booking_v1_booking_error_reason_proto_rawDesc = "" +
	"\n" +
	"%booking/v1/booking_error_reason.proto\x12\x0eapi.booking.v1*\x89\x03\n" +
	"\vErrorReason\x12\x17\n" +
	"\x13BOOKING_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BOOKING_NOT_FOUND\x10\x01\x12\x16\n" +
	"\x12INVALID_BOOKING_ID\x10\x02\x12\x13\n" +
	"\x0fINVALID_USER_ID\x10\x03\x12\x14\n" +
	"\x10INVALID_HOTEL_ID\x10\x04\x12\x18\n" +
	"\x14INVALID_BOOKING_DATE\x10\x05\x12\x16\n" +
	"\x12INVALID_PARAMETERS\x10\x06\x12\x10\n" +
	"\fUNAUTHORIZED\x10\a\x12\x12\n" +
	"\x0eDATABASE_ERROR\x10\b\x12\x1d\n" +
	"\x19BOOKING_ALREADY_CANCELLED\x10\t\x12\x1b\n" +
	"\x17BOOKING_CREATION_FAILED\x10\n" +
	"\x12\x1a\n" +
	"\x15BOOKING_JOB_NOT_FOUND\x10\xa8F\x12 \n" +
	"\x1bBOOKING_JOB_ALREADY_RUNNING\x10\xa9F\x12\x1c\n" +
	"\x17BOOKING_JOB_NOT_RUNNING\x10\xaaF\x12\x17\n" +
	"\x12BOOKING_JOB_FAILED\x10\xabFB5\n" +
	"\x0eapi.booking.v1P\x01Z!yinni_travel_backend/api/booking/v1;v1b\x06proto3"

var (
	file_booking_v1_booking_error_reason_proto_rawDescOnce sync.Once
	file_booking_v1_booking_error_reason_proto_rawDescData []byte
)

func file_booking_v1_booking_error_reason_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_error_reason_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_error_reason_proto_rawDesc), len(file_booking_v1_booking_error_reason_proto_rawDesc)))
	})
	return file_booking_v1_booking_error_reason_proto_rawDescData
}

var file_booking_v1_booking_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_booking_v1_booking_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.booking.v1.ErrorReason
}
var file_booking_v1_booking_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_error_reason_proto_init() }
func file_booking_v1_booking_error_reason_proto_init() {
	if File_booking_v1_booking_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_error_reason_proto_rawDesc), len(file_booking_v1_booking_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_booking_error_reason_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_error_reason_proto_depIdxs,
		EnumInfos:         file_booking_v1_booking_error_reason_proto_enumTypes,
	}.Build()
	File_booking_v1_booking_error_reason_proto = out.File
	file_booking_v1_booking_error_reason_proto_goTypes = nil
	file_booking_v1_booking_error_reason_proto_depIdxs = nil
}
