// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HotelsColumns holds the columns for the "hotels" table.
	HotelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "original_id", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "brand", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "actual_price", Type: field.TypeFloat32, Nullable: true},
		{Name: "selling_price", Type: field.TypeFloat32, Nullable: true},
		{Name: "discount", Type: field.TypeString, Nullable: true},
		{Name: "category", Type: field.TypeString},
		{Name: "sub_category", Type: field.TypeString},
		{Name: "out_of_stock", Type: field.TypeBool, Default: false},
		{Name: "seller", Type: field.TypeString, Nullable: true},
		{Name: "average_rating", Type: field.TypeString, Nullable: true},
		{Name: "image", Type: field.TypeString, Nullable: true},
		{Name: "hotel_details", Type: field.TypeJSON, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true, Size: 2048},
		{Name: "pid", Type: field.TypeString, Unique: true},
		{Name: "style_code", Type: field.TypeString, Nullable: true},
		{Name: "crawled_at", Type: field.TypeTime, Nullable: true},
		{Name: "embedding", Type: field.TypeJSON, Nullable: true},
		{Name: "search_keywords", Type: field.TypeJSON, Nullable: true},
		{Name: "featured", Type: field.TypeBool, Default: false},
		{Name: "view_count", Type: field.TypeInt, Default: 0},
		{Name: "click_count", Type: field.TypeInt, Default: 0},
		{Name: "price_numeric", Type: field.TypeInt, Nullable: true},
		{Name: "rating_numeric", Type: field.TypeFloat64, Nullable: true},
	}
	// HotelsTable holds the schema information for the "hotels" table.
	HotelsTable = &schema.Table{
		Name:       "hotels",
		Columns:    HotelsColumns,
		PrimaryKey: []*schema.Column{HotelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "hotel_pid",
				Unique:  true,
				Columns: []*schema.Column{HotelsColumns[18]},
			},
			{
				Name:    "hotel_original_id",
				Unique:  true,
				Columns: []*schema.Column{HotelsColumns[3]},
			},
			{
				Name:    "hotel_brand",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[5]},
			},
			{
				Name:    "hotel_category",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[10]},
			},
			{
				Name:    "hotel_sub_category",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[11]},
			},
			{
				Name:    "hotel_price_numeric",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[26]},
			},
			{
				Name:    "hotel_rating_numeric",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[27]},
			},
			{
				Name:    "hotel_out_of_stock",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[12]},
			},
			{
				Name:    "hotel_featured",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[23]},
			},
			{
				Name:    "hotel_category_sub_category",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[10], HotelsColumns[11]},
			},
			{
				Name:    "hotel_brand_category",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[5], HotelsColumns[10]},
			},
			{
				Name:    "hotel_category_price_numeric",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[10], HotelsColumns[26]},
			},
			{
				Name:    "hotel_category_rating_numeric",
				Unique:  false,
				Columns: []*schema.Column{HotelsColumns[10], HotelsColumns[27]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HotelsTable,
	}
)

func init() {
}
