// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yinni_travel_backend/ent/hotel"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HotelCreate is the builder for creating a Hotel entity.
type HotelCreate struct {
	config
	mutation *HotelMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *HotelCreate) SetCreateTime(v time.Time) *HotelCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *HotelCreate) SetNillableCreateTime(v *time.Time) *HotelCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *HotelCreate) SetUpdateTime(v time.Time) *HotelCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *HotelCreate) SetNillableUpdateTime(v *time.Time) *HotelCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetOriginalID sets the "original_id" field.
func (_c *HotelCreate) SetOriginalID(v string) *HotelCreate {
	_c.mutation.SetOriginalID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *HotelCreate) SetTitle(v string) *HotelCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBrand sets the "brand" field.
func (_c *HotelCreate) SetBrand(v string) *HotelCreate {
	_c.mutation.SetBrand(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *HotelCreate) SetDescription(v string) *HotelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *HotelCreate) SetNillableDescription(v *string) *HotelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetActualPrice sets the "actual_price" field.
func (_c *HotelCreate) SetActualPrice(v float32) *HotelCreate {
	_c.mutation.SetActualPrice(v)
	return _c
}

// SetNillableActualPrice sets the "actual_price" field if the given value is not nil.
func (_c *HotelCreate) SetNillableActualPrice(v *float32) *HotelCreate {
	if v != nil {
		_c.SetActualPrice(*v)
	}
	return _c
}

// SetSellingPrice sets the "selling_price" field.
func (_c *HotelCreate) SetSellingPrice(v float32) *HotelCreate {
	_c.mutation.SetSellingPrice(v)
	return _c
}

// SetNillableSellingPrice sets the "selling_price" field if the given value is not nil.
func (_c *HotelCreate) SetNillableSellingPrice(v *float32) *HotelCreate {
	if v != nil {
		_c.SetSellingPrice(*v)
	}
	return _c
}

// SetDiscount sets the "discount" field.
func (_c *HotelCreate) SetDiscount(v string) *HotelCreate {
	_c.mutation.SetDiscount(v)
	return _c
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_c *HotelCreate) SetNillableDiscount(v *string) *HotelCreate {
	if v != nil {
		_c.SetDiscount(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *HotelCreate) SetCategory(v string) *HotelCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetSubCategory sets the "sub_category" field.
func (_c *HotelCreate) SetSubCategory(v string) *HotelCreate {
	_c.mutation.SetSubCategory(v)
	return _c
}

// SetOutOfStock sets the "out_of_stock" field.
func (_c *HotelCreate) SetOutOfStock(v bool) *HotelCreate {
	_c.mutation.SetOutOfStock(v)
	return _c
}

// SetNillableOutOfStock sets the "out_of_stock" field if the given value is not nil.
func (_c *HotelCreate) SetNillableOutOfStock(v *bool) *HotelCreate {
	if v != nil {
		_c.SetOutOfStock(*v)
	}
	return _c
}

// SetSeller sets the "seller" field.
func (_c *HotelCreate) SetSeller(v string) *HotelCreate {
	_c.mutation.SetSeller(v)
	return _c
}

// SetNillableSeller sets the "seller" field if the given value is not nil.
func (_c *HotelCreate) SetNillableSeller(v *string) *HotelCreate {
	if v != nil {
		_c.SetSeller(*v)
	}
	return _c
}

// SetAverageRating sets the "average_rating" field.
func (_c *HotelCreate) SetAverageRating(v string) *HotelCreate {
	_c.mutation.SetAverageRating(v)
	return _c
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_c *HotelCreate) SetNillableAverageRating(v *string) *HotelCreate {
	if v != nil {
		_c.SetAverageRating(*v)
	}
	return _c
}

// SetImage sets the "image" field.
func (_c *HotelCreate) SetImage(v string) *HotelCreate {
	_c.mutation.SetImage(v)
	return _c
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_c *HotelCreate) SetNillableImage(v *string) *HotelCreate {
	if v != nil {
		_c.SetImage(*v)
	}
	return _c
}

// SetHotelDetails sets the "hotel_details" field.
func (_c *HotelCreate) SetHotelDetails(v []map[string]string) *HotelCreate {
	_c.mutation.SetHotelDetails(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *HotelCreate) SetURL(v string) *HotelCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *HotelCreate) SetNillableURL(v *string) *HotelCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetPid sets the "pid" field.
func (_c *HotelCreate) SetPid(v string) *HotelCreate {
	_c.mutation.SetPid(v)
	return _c
}

// SetStyleCode sets the "style_code" field.
func (_c *HotelCreate) SetStyleCode(v string) *HotelCreate {
	_c.mutation.SetStyleCode(v)
	return _c
}

// SetNillableStyleCode sets the "style_code" field if the given value is not nil.
func (_c *HotelCreate) SetNillableStyleCode(v *string) *HotelCreate {
	if v != nil {
		_c.SetStyleCode(*v)
	}
	return _c
}

// SetCrawledAt sets the "crawled_at" field.
func (_c *HotelCreate) SetCrawledAt(v time.Time) *HotelCreate {
	_c.mutation.SetCrawledAt(v)
	return _c
}

// SetNillableCrawledAt sets the "crawled_at" field if the given value is not nil.
func (_c *HotelCreate) SetNillableCrawledAt(v *time.Time) *HotelCreate {
	if v != nil {
		_c.SetCrawledAt(*v)
	}
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *HotelCreate) SetEmbedding(v []float32) *HotelCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetSearchKeywords sets the "search_keywords" field.
func (_c *HotelCreate) SetSearchKeywords(v []string) *HotelCreate {
	_c.mutation.SetSearchKeywords(v)
	return _c
}

// SetFeatured sets the "featured" field.
func (_c *HotelCreate) SetFeatured(v bool) *HotelCreate {
	_c.mutation.SetFeatured(v)
	return _c
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_c *HotelCreate) SetNillableFeatured(v *bool) *HotelCreate {
	if v != nil {
		_c.SetFeatured(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *HotelCreate) SetViewCount(v int) *HotelCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *HotelCreate) SetNillableViewCount(v *int) *HotelCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetClickCount sets the "click_count" field.
func (_c *HotelCreate) SetClickCount(v int) *HotelCreate {
	_c.mutation.SetClickCount(v)
	return _c
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_c *HotelCreate) SetNillableClickCount(v *int) *HotelCreate {
	if v != nil {
		_c.SetClickCount(*v)
	}
	return _c
}

// SetPriceNumeric sets the "price_numeric" field.
func (_c *HotelCreate) SetPriceNumeric(v int) *HotelCreate {
	_c.mutation.SetPriceNumeric(v)
	return _c
}

// SetNillablePriceNumeric sets the "price_numeric" field if the given value is not nil.
func (_c *HotelCreate) SetNillablePriceNumeric(v *int) *HotelCreate {
	if v != nil {
		_c.SetPriceNumeric(*v)
	}
	return _c
}

// SetRatingNumeric sets the "rating_numeric" field.
func (_c *HotelCreate) SetRatingNumeric(v float64) *HotelCreate {
	_c.mutation.SetRatingNumeric(v)
	return _c
}

// SetNillableRatingNumeric sets the "rating_numeric" field if the given value is not nil.
func (_c *HotelCreate) SetNillableRatingNumeric(v *float64) *HotelCreate {
	if v != nil {
		_c.SetRatingNumeric(*v)
	}
	return _c
}

// Mutation returns the HotelMutation object of the builder.
func (_c *HotelCreate) Mutation() *HotelMutation {
	return _c.mutation
}

// Save creates the Hotel in the database.
func (_c *HotelCreate) Save(ctx context.Context) (*Hotel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HotelCreate) SaveX(ctx context.Context) *Hotel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HotelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HotelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HotelCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := hotel.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := hotel.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.OutOfStock(); !ok {
		v := hotel.DefaultOutOfStock
		_c.mutation.SetOutOfStock(v)
	}
	if _, ok := _c.mutation.Featured(); !ok {
		v := hotel.DefaultFeatured
		_c.mutation.SetFeatured(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := hotel.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.ClickCount(); !ok {
		v := hotel.DefaultClickCount
		_c.mutation.SetClickCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HotelCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Hotel.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Hotel.update_time"`)}
	}
	if _, ok := _c.mutation.OriginalID(); !ok {
		return &ValidationError{Name: "original_id", err: errors.New(`ent: missing required field "Hotel.original_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Hotel.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := hotel.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Hotel.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Brand(); !ok {
		return &ValidationError{Name: "brand", err: errors.New(`ent: missing required field "Hotel.brand"`)}
	}
	if v, ok := _c.mutation.Brand(); ok {
		if err := hotel.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Hotel.brand": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Hotel.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := hotel.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Hotel.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubCategory(); !ok {
		return &ValidationError{Name: "sub_category", err: errors.New(`ent: missing required field "Hotel.sub_category"`)}
	}
	if v, ok := _c.mutation.SubCategory(); ok {
		if err := hotel.SubCategoryValidator(v); err != nil {
			return &ValidationError{Name: "sub_category", err: fmt.Errorf(`ent: validator failed for field "Hotel.sub_category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OutOfStock(); !ok {
		return &ValidationError{Name: "out_of_stock", err: errors.New(`ent: missing required field "Hotel.out_of_stock"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := hotel.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Hotel.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pid(); !ok {
		return &ValidationError{Name: "pid", err: errors.New(`ent: missing required field "Hotel.pid"`)}
	}
	if _, ok := _c.mutation.Featured(); !ok {
		return &ValidationError{Name: "featured", err: errors.New(`ent: missing required field "Hotel.featured"`)}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Hotel.view_count"`)}
	}
	if _, ok := _c.mutation.ClickCount(); !ok {
		return &ValidationError{Name: "click_count", err: errors.New(`ent: missing required field "Hotel.click_count"`)}
	}
	if v, ok := _c.mutation.PriceNumeric(); ok {
		if err := hotel.PriceNumericValidator(v); err != nil {
			return &ValidationError{Name: "price_numeric", err: fmt.Errorf(`ent: validator failed for field "Hotel.price_numeric": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RatingNumeric(); ok {
		if err := hotel.RatingNumericValidator(v); err != nil {
			return &ValidationError{Name: "rating_numeric", err: fmt.Errorf(`ent: validator failed for field "Hotel.rating_numeric": %w`, err)}
		}
	}
	return nil
}

func (_c *HotelCreate) sqlSave(ctx context.Context) (*Hotel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HotelCreate) createSpec() (*Hotel, *sqlgraph.CreateSpec) {
	var (
		_node = &Hotel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hotel.Table, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(hotel.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(hotel.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.OriginalID(); ok {
		_spec.SetField(hotel.FieldOriginalID, field.TypeString, value)
		_node.OriginalID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(hotel.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Brand(); ok {
		_spec.SetField(hotel.FieldBrand, field.TypeString, value)
		_node.Brand = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(hotel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ActualPrice(); ok {
		_spec.SetField(hotel.FieldActualPrice, field.TypeFloat32, value)
		_node.ActualPrice = value
	}
	if value, ok := _c.mutation.SellingPrice(); ok {
		_spec.SetField(hotel.FieldSellingPrice, field.TypeFloat32, value)
		_node.SellingPrice = value
	}
	if value, ok := _c.mutation.Discount(); ok {
		_spec.SetField(hotel.FieldDiscount, field.TypeString, value)
		_node.Discount = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(hotel.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.SubCategory(); ok {
		_spec.SetField(hotel.FieldSubCategory, field.TypeString, value)
		_node.SubCategory = value
	}
	if value, ok := _c.mutation.OutOfStock(); ok {
		_spec.SetField(hotel.FieldOutOfStock, field.TypeBool, value)
		_node.OutOfStock = value
	}
	if value, ok := _c.mutation.Seller(); ok {
		_spec.SetField(hotel.FieldSeller, field.TypeString, value)
		_node.Seller = value
	}
	if value, ok := _c.mutation.AverageRating(); ok {
		_spec.SetField(hotel.FieldAverageRating, field.TypeString, value)
		_node.AverageRating = value
	}
	if value, ok := _c.mutation.Image(); ok {
		_spec.SetField(hotel.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if value, ok := _c.mutation.HotelDetails(); ok {
		_spec.SetField(hotel.FieldHotelDetails, field.TypeJSON, value)
		_node.HotelDetails = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(hotel.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Pid(); ok {
		_spec.SetField(hotel.FieldPid, field.TypeString, value)
		_node.Pid = value
	}
	if value, ok := _c.mutation.StyleCode(); ok {
		_spec.SetField(hotel.FieldStyleCode, field.TypeString, value)
		_node.StyleCode = value
	}
	if value, ok := _c.mutation.CrawledAt(); ok {
		_spec.SetField(hotel.FieldCrawledAt, field.TypeTime, value)
		_node.CrawledAt = value
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(hotel.FieldEmbedding, field.TypeJSON, value)
		_node.Embedding = value
	}
	if value, ok := _c.mutation.SearchKeywords(); ok {
		_spec.SetField(hotel.FieldSearchKeywords, field.TypeJSON, value)
		_node.SearchKeywords = value
	}
	if value, ok := _c.mutation.Featured(); ok {
		_spec.SetField(hotel.FieldFeatured, field.TypeBool, value)
		_node.Featured = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(hotel.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.ClickCount(); ok {
		_spec.SetField(hotel.FieldClickCount, field.TypeInt, value)
		_node.ClickCount = value
	}
	if value, ok := _c.mutation.PriceNumeric(); ok {
		_spec.SetField(hotel.FieldPriceNumeric, field.TypeInt, value)
		_node.PriceNumeric = value
	}
	if value, ok := _c.mutation.RatingNumeric(); ok {
		_spec.SetField(hotel.FieldRatingNumeric, field.TypeFloat64, value)
		_node.RatingNumeric = value
	}
	return _node, _spec
}

// HotelCreateBulk is the builder for creating many Hotel entities in bulk.
type HotelCreateBulk struct {
	config
	err      error
	builders []*HotelCreate
}

// Save creates the Hotel entities in the database.
func (_c *HotelCreateBulk) Save(ctx context.Context) ([]*Hotel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Hotel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HotelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HotelCreateBulk) SaveX(ctx context.Context) []*Hotel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HotelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HotelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
