// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yinni-travel-backend/ent/hotel"
	"yinni-travel-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// HotelUpdate is the builder for updating Hotel entities.
type HotelUpdate struct {
	config
	hooks    []Hook
	mutation *HotelMutation
}

// Where appends a list predicates to the HotelUpdate builder.
func (_u *HotelUpdate) Where(ps ...predicate.Hotel) *HotelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *HotelUpdate) SetUpdateTime(v time.Time) *HotelUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetOriginalID sets the "original_id" field.
func (_u *HotelUpdate) SetOriginalID(v string) *HotelUpdate {
	_u.mutation.SetOriginalID(v)
	return _u
}

// SetNillableOriginalID sets the "original_id" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableOriginalID(v *string) *HotelUpdate {
	if v != nil {
		_u.SetOriginalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *HotelUpdate) SetTitle(v string) *HotelUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableTitle(v *string) *HotelUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBrand sets the "brand" field.
func (_u *HotelUpdate) SetBrand(v string) *HotelUpdate {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableBrand(v *string) *HotelUpdate {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HotelUpdate) SetDescription(v string) *HotelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableDescription(v *string) *HotelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HotelUpdate) ClearDescription() *HotelUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetActualPrice sets the "actual_price" field.
func (_u *HotelUpdate) SetActualPrice(v float32) *HotelUpdate {
	_u.mutation.ResetActualPrice()
	_u.mutation.SetActualPrice(v)
	return _u
}

// SetNillableActualPrice sets the "actual_price" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableActualPrice(v *float32) *HotelUpdate {
	if v != nil {
		_u.SetActualPrice(*v)
	}
	return _u
}

// AddActualPrice adds value to the "actual_price" field.
func (_u *HotelUpdate) AddActualPrice(v float32) *HotelUpdate {
	_u.mutation.AddActualPrice(v)
	return _u
}

// ClearActualPrice clears the value of the "actual_price" field.
func (_u *HotelUpdate) ClearActualPrice() *HotelUpdate {
	_u.mutation.ClearActualPrice()
	return _u
}

// SetSellingPrice sets the "selling_price" field.
func (_u *HotelUpdate) SetSellingPrice(v float32) *HotelUpdate {
	_u.mutation.ResetSellingPrice()
	_u.mutation.SetSellingPrice(v)
	return _u
}

// SetNillableSellingPrice sets the "selling_price" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableSellingPrice(v *float32) *HotelUpdate {
	if v != nil {
		_u.SetSellingPrice(*v)
	}
	return _u
}

// AddSellingPrice adds value to the "selling_price" field.
func (_u *HotelUpdate) AddSellingPrice(v float32) *HotelUpdate {
	_u.mutation.AddSellingPrice(v)
	return _u
}

// ClearSellingPrice clears the value of the "selling_price" field.
func (_u *HotelUpdate) ClearSellingPrice() *HotelUpdate {
	_u.mutation.ClearSellingPrice()
	return _u
}

// SetDiscount sets the "discount" field.
func (_u *HotelUpdate) SetDiscount(v string) *HotelUpdate {
	_u.mutation.SetDiscount(v)
	return _u
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableDiscount(v *string) *HotelUpdate {
	if v != nil {
		_u.SetDiscount(*v)
	}
	return _u
}

// ClearDiscount clears the value of the "discount" field.
func (_u *HotelUpdate) ClearDiscount() *HotelUpdate {
	_u.mutation.ClearDiscount()
	return _u
}

// SetCategory sets the "category" field.
func (_u *HotelUpdate) SetCategory(v string) *HotelUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableCategory(v *string) *HotelUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSubCategory sets the "sub_category" field.
func (_u *HotelUpdate) SetSubCategory(v string) *HotelUpdate {
	_u.mutation.SetSubCategory(v)
	return _u
}

// SetNillableSubCategory sets the "sub_category" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableSubCategory(v *string) *HotelUpdate {
	if v != nil {
		_u.SetSubCategory(*v)
	}
	return _u
}

// SetOutOfStock sets the "out_of_stock" field.
func (_u *HotelUpdate) SetOutOfStock(v bool) *HotelUpdate {
	_u.mutation.SetOutOfStock(v)
	return _u
}

// SetNillableOutOfStock sets the "out_of_stock" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableOutOfStock(v *bool) *HotelUpdate {
	if v != nil {
		_u.SetOutOfStock(*v)
	}
	return _u
}

// SetSeller sets the "seller" field.
func (_u *HotelUpdate) SetSeller(v string) *HotelUpdate {
	_u.mutation.SetSeller(v)
	return _u
}

// SetNillableSeller sets the "seller" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableSeller(v *string) *HotelUpdate {
	if v != nil {
		_u.SetSeller(*v)
	}
	return _u
}

// ClearSeller clears the value of the "seller" field.
func (_u *HotelUpdate) ClearSeller() *HotelUpdate {
	_u.mutation.ClearSeller()
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *HotelUpdate) SetAverageRating(v string) *HotelUpdate {
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableAverageRating(v *string) *HotelUpdate {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// ClearAverageRating clears the value of the "average_rating" field.
func (_u *HotelUpdate) ClearAverageRating() *HotelUpdate {
	_u.mutation.ClearAverageRating()
	return _u
}

// SetImage sets the "image" field.
func (_u *HotelUpdate) SetImage(v string) *HotelUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableImage(v *string) *HotelUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *HotelUpdate) ClearImage() *HotelUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetHotelDetails sets the "hotel_details" field.
func (_u *HotelUpdate) SetHotelDetails(v []map[string]string) *HotelUpdate {
	_u.mutation.SetHotelDetails(v)
	return _u
}

// AppendHotelDetails appends value to the "hotel_details" field.
func (_u *HotelUpdate) AppendHotelDetails(v []map[string]string) *HotelUpdate {
	_u.mutation.AppendHotelDetails(v)
	return _u
}

// ClearHotelDetails clears the value of the "hotel_details" field.
func (_u *HotelUpdate) ClearHotelDetails() *HotelUpdate {
	_u.mutation.ClearHotelDetails()
	return _u
}

// SetURL sets the "url" field.
func (_u *HotelUpdate) SetURL(v string) *HotelUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableURL(v *string) *HotelUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *HotelUpdate) ClearURL() *HotelUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetPid sets the "pid" field.
func (_u *HotelUpdate) SetPid(v string) *HotelUpdate {
	_u.mutation.SetPid(v)
	return _u
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_u *HotelUpdate) SetNillablePid(v *string) *HotelUpdate {
	if v != nil {
		_u.SetPid(*v)
	}
	return _u
}

// SetStyleCode sets the "style_code" field.
func (_u *HotelUpdate) SetStyleCode(v string) *HotelUpdate {
	_u.mutation.SetStyleCode(v)
	return _u
}

// SetNillableStyleCode sets the "style_code" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableStyleCode(v *string) *HotelUpdate {
	if v != nil {
		_u.SetStyleCode(*v)
	}
	return _u
}

// ClearStyleCode clears the value of the "style_code" field.
func (_u *HotelUpdate) ClearStyleCode() *HotelUpdate {
	_u.mutation.ClearStyleCode()
	return _u
}

// SetCrawledAt sets the "crawled_at" field.
func (_u *HotelUpdate) SetCrawledAt(v time.Time) *HotelUpdate {
	_u.mutation.SetCrawledAt(v)
	return _u
}

// SetNillableCrawledAt sets the "crawled_at" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableCrawledAt(v *time.Time) *HotelUpdate {
	if v != nil {
		_u.SetCrawledAt(*v)
	}
	return _u
}

// ClearCrawledAt clears the value of the "crawled_at" field.
func (_u *HotelUpdate) ClearCrawledAt() *HotelUpdate {
	_u.mutation.ClearCrawledAt()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *HotelUpdate) SetEmbedding(v []float32) *HotelUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *HotelUpdate) AppendEmbedding(v []float32) *HotelUpdate {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *HotelUpdate) ClearEmbedding() *HotelUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetSearchKeywords sets the "search_keywords" field.
func (_u *HotelUpdate) SetSearchKeywords(v []string) *HotelUpdate {
	_u.mutation.SetSearchKeywords(v)
	return _u
}

// AppendSearchKeywords appends value to the "search_keywords" field.
func (_u *HotelUpdate) AppendSearchKeywords(v []string) *HotelUpdate {
	_u.mutation.AppendSearchKeywords(v)
	return _u
}

// ClearSearchKeywords clears the value of the "search_keywords" field.
func (_u *HotelUpdate) ClearSearchKeywords() *HotelUpdate {
	_u.mutation.ClearSearchKeywords()
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *HotelUpdate) SetFeatured(v bool) *HotelUpdate {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableFeatured(v *bool) *HotelUpdate {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *HotelUpdate) SetViewCount(v int) *HotelUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableViewCount(v *int) *HotelUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *HotelUpdate) AddViewCount(v int) *HotelUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *HotelUpdate) SetClickCount(v int) *HotelUpdate {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableClickCount(v *int) *HotelUpdate {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *HotelUpdate) AddClickCount(v int) *HotelUpdate {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetPriceNumeric sets the "price_numeric" field.
func (_u *HotelUpdate) SetPriceNumeric(v int) *HotelUpdate {
	_u.mutation.ResetPriceNumeric()
	_u.mutation.SetPriceNumeric(v)
	return _u
}

// SetNillablePriceNumeric sets the "price_numeric" field if the given value is not nil.
func (_u *HotelUpdate) SetNillablePriceNumeric(v *int) *HotelUpdate {
	if v != nil {
		_u.SetPriceNumeric(*v)
	}
	return _u
}

// AddPriceNumeric adds value to the "price_numeric" field.
func (_u *HotelUpdate) AddPriceNumeric(v int) *HotelUpdate {
	_u.mutation.AddPriceNumeric(v)
	return _u
}

// ClearPriceNumeric clears the value of the "price_numeric" field.
func (_u *HotelUpdate) ClearPriceNumeric() *HotelUpdate {
	_u.mutation.ClearPriceNumeric()
	return _u
}

// SetRatingNumeric sets the "rating_numeric" field.
func (_u *HotelUpdate) SetRatingNumeric(v float64) *HotelUpdate {
	_u.mutation.ResetRatingNumeric()
	_u.mutation.SetRatingNumeric(v)
	return _u
}

// SetNillableRatingNumeric sets the "rating_numeric" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableRatingNumeric(v *float64) *HotelUpdate {
	if v != nil {
		_u.SetRatingNumeric(*v)
	}
	return _u
}

// AddRatingNumeric adds value to the "rating_numeric" field.
func (_u *HotelUpdate) AddRatingNumeric(v float64) *HotelUpdate {
	_u.mutation.AddRatingNumeric(v)
	return _u
}

// ClearRatingNumeric clears the value of the "rating_numeric" field.
func (_u *HotelUpdate) ClearRatingNumeric() *HotelUpdate {
	_u.mutation.ClearRatingNumeric()
	return _u
}

// Mutation returns the HotelMutation object of the builder.
func (_u *HotelUpdate) Mutation() *HotelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HotelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HotelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HotelUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := hotel.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HotelUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := hotel.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Hotel.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Brand(); ok {
		if err := hotel.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Hotel.brand": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := hotel.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Hotel.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubCategory(); ok {
		if err := hotel.SubCategoryValidator(v); err != nil {
			return &ValidationError{Name: "sub_category", err: fmt.Errorf(`ent: validator failed for field "Hotel.sub_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := hotel.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Hotel.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceNumeric(); ok {
		if err := hotel.PriceNumericValidator(v); err != nil {
			return &ValidationError{Name: "price_numeric", err: fmt.Errorf(`ent: validator failed for field "Hotel.price_numeric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RatingNumeric(); ok {
		if err := hotel.RatingNumericValidator(v); err != nil {
			return &ValidationError{Name: "rating_numeric", err: fmt.Errorf(`ent: validator failed for field "Hotel.rating_numeric": %w`, err)}
		}
	}
	return nil
}

func (_u *HotelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hotel.Table, hotel.Columns, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(hotel.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OriginalID(); ok {
		_spec.SetField(hotel.FieldOriginalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(hotel.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(hotel.FieldBrand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(hotel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(hotel.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ActualPrice(); ok {
		_spec.SetField(hotel.FieldActualPrice, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedActualPrice(); ok {
		_spec.AddField(hotel.FieldActualPrice, field.TypeFloat32, value)
	}
	if _u.mutation.ActualPriceCleared() {
		_spec.ClearField(hotel.FieldActualPrice, field.TypeFloat32)
	}
	if value, ok := _u.mutation.SellingPrice(); ok {
		_spec.SetField(hotel.FieldSellingPrice, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedSellingPrice(); ok {
		_spec.AddField(hotel.FieldSellingPrice, field.TypeFloat32, value)
	}
	if _u.mutation.SellingPriceCleared() {
		_spec.ClearField(hotel.FieldSellingPrice, field.TypeFloat32)
	}
	if value, ok := _u.mutation.Discount(); ok {
		_spec.SetField(hotel.FieldDiscount, field.TypeString, value)
	}
	if _u.mutation.DiscountCleared() {
		_spec.ClearField(hotel.FieldDiscount, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(hotel.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubCategory(); ok {
		_spec.SetField(hotel.FieldSubCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutOfStock(); ok {
		_spec.SetField(hotel.FieldOutOfStock, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Seller(); ok {
		_spec.SetField(hotel.FieldSeller, field.TypeString, value)
	}
	if _u.mutation.SellerCleared() {
		_spec.ClearField(hotel.FieldSeller, field.TypeString)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(hotel.FieldAverageRating, field.TypeString, value)
	}
	if _u.mutation.AverageRatingCleared() {
		_spec.ClearField(hotel.FieldAverageRating, field.TypeString)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(hotel.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(hotel.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.HotelDetails(); ok {
		_spec.SetField(hotel.FieldHotelDetails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHotelDetails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldHotelDetails, value)
		})
	}
	if _u.mutation.HotelDetailsCleared() {
		_spec.ClearField(hotel.FieldHotelDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(hotel.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(hotel.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Pid(); ok {
		_spec.SetField(hotel.FieldPid, field.TypeString, value)
	}
	if value, ok := _u.mutation.StyleCode(); ok {
		_spec.SetField(hotel.FieldStyleCode, field.TypeString, value)
	}
	if _u.mutation.StyleCodeCleared() {
		_spec.ClearField(hotel.FieldStyleCode, field.TypeString)
	}
	if value, ok := _u.mutation.CrawledAt(); ok {
		_spec.SetField(hotel.FieldCrawledAt, field.TypeTime, value)
	}
	if _u.mutation.CrawledAtCleared() {
		_spec.ClearField(hotel.FieldCrawledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(hotel.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldEmbedding, value)
		})
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(hotel.FieldEmbedding, field.TypeJSON)
	}
	if value, ok := _u.mutation.SearchKeywords(); ok {
		_spec.SetField(hotel.FieldSearchKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSearchKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldSearchKeywords, value)
		})
	}
	if _u.mutation.SearchKeywordsCleared() {
		_spec.ClearField(hotel.FieldSearchKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(hotel.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(hotel.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(hotel.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(hotel.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(hotel.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PriceNumeric(); ok {
		_spec.SetField(hotel.FieldPriceNumeric, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriceNumeric(); ok {
		_spec.AddField(hotel.FieldPriceNumeric, field.TypeInt, value)
	}
	if _u.mutation.PriceNumericCleared() {
		_spec.ClearField(hotel.FieldPriceNumeric, field.TypeInt)
	}
	if value, ok := _u.mutation.RatingNumeric(); ok {
		_spec.SetField(hotel.FieldRatingNumeric, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatingNumeric(); ok {
		_spec.AddField(hotel.FieldRatingNumeric, field.TypeFloat64, value)
	}
	if _u.mutation.RatingNumericCleared() {
		_spec.ClearField(hotel.FieldRatingNumeric, field.TypeFloat64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HotelUpdateOne is the builder for updating a single Hotel entity.
type HotelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HotelMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *HotelUpdateOne) SetUpdateTime(v time.Time) *HotelUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetOriginalID sets the "original_id" field.
func (_u *HotelUpdateOne) SetOriginalID(v string) *HotelUpdateOne {
	_u.mutation.SetOriginalID(v)
	return _u
}

// SetNillableOriginalID sets the "original_id" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableOriginalID(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetOriginalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *HotelUpdateOne) SetTitle(v string) *HotelUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableTitle(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBrand sets the "brand" field.
func (_u *HotelUpdateOne) SetBrand(v string) *HotelUpdateOne {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableBrand(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HotelUpdateOne) SetDescription(v string) *HotelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableDescription(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HotelUpdateOne) ClearDescription() *HotelUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetActualPrice sets the "actual_price" field.
func (_u *HotelUpdateOne) SetActualPrice(v float32) *HotelUpdateOne {
	_u.mutation.ResetActualPrice()
	_u.mutation.SetActualPrice(v)
	return _u
}

// SetNillableActualPrice sets the "actual_price" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableActualPrice(v *float32) *HotelUpdateOne {
	if v != nil {
		_u.SetActualPrice(*v)
	}
	return _u
}

// AddActualPrice adds value to the "actual_price" field.
func (_u *HotelUpdateOne) AddActualPrice(v float32) *HotelUpdateOne {
	_u.mutation.AddActualPrice(v)
	return _u
}

// ClearActualPrice clears the value of the "actual_price" field.
func (_u *HotelUpdateOne) ClearActualPrice() *HotelUpdateOne {
	_u.mutation.ClearActualPrice()
	return _u
}

// SetSellingPrice sets the "selling_price" field.
func (_u *HotelUpdateOne) SetSellingPrice(v float32) *HotelUpdateOne {
	_u.mutation.ResetSellingPrice()
	_u.mutation.SetSellingPrice(v)
	return _u
}

// SetNillableSellingPrice sets the "selling_price" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableSellingPrice(v *float32) *HotelUpdateOne {
	if v != nil {
		_u.SetSellingPrice(*v)
	}
	return _u
}

// AddSellingPrice adds value to the "selling_price" field.
func (_u *HotelUpdateOne) AddSellingPrice(v float32) *HotelUpdateOne {
	_u.mutation.AddSellingPrice(v)
	return _u
}

// ClearSellingPrice clears the value of the "selling_price" field.
func (_u *HotelUpdateOne) ClearSellingPrice() *HotelUpdateOne {
	_u.mutation.ClearSellingPrice()
	return _u
}

// SetDiscount sets the "discount" field.
func (_u *HotelUpdateOne) SetDiscount(v string) *HotelUpdateOne {
	_u.mutation.SetDiscount(v)
	return _u
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableDiscount(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetDiscount(*v)
	}
	return _u
}

// ClearDiscount clears the value of the "discount" field.
func (_u *HotelUpdateOne) ClearDiscount() *HotelUpdateOne {
	_u.mutation.ClearDiscount()
	return _u
}

// SetCategory sets the "category" field.
func (_u *HotelUpdateOne) SetCategory(v string) *HotelUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableCategory(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSubCategory sets the "sub_category" field.
func (_u *HotelUpdateOne) SetSubCategory(v string) *HotelUpdateOne {
	_u.mutation.SetSubCategory(v)
	return _u
}

// SetNillableSubCategory sets the "sub_category" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableSubCategory(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetSubCategory(*v)
	}
	return _u
}

// SetOutOfStock sets the "out_of_stock" field.
func (_u *HotelUpdateOne) SetOutOfStock(v bool) *HotelUpdateOne {
	_u.mutation.SetOutOfStock(v)
	return _u
}

// SetNillableOutOfStock sets the "out_of_stock" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableOutOfStock(v *bool) *HotelUpdateOne {
	if v != nil {
		_u.SetOutOfStock(*v)
	}
	return _u
}

// SetSeller sets the "seller" field.
func (_u *HotelUpdateOne) SetSeller(v string) *HotelUpdateOne {
	_u.mutation.SetSeller(v)
	return _u
}

// SetNillableSeller sets the "seller" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableSeller(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetSeller(*v)
	}
	return _u
}

// ClearSeller clears the value of the "seller" field.
func (_u *HotelUpdateOne) ClearSeller() *HotelUpdateOne {
	_u.mutation.ClearSeller()
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *HotelUpdateOne) SetAverageRating(v string) *HotelUpdateOne {
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableAverageRating(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// ClearAverageRating clears the value of the "average_rating" field.
func (_u *HotelUpdateOne) ClearAverageRating() *HotelUpdateOne {
	_u.mutation.ClearAverageRating()
	return _u
}

// SetImage sets the "image" field.
func (_u *HotelUpdateOne) SetImage(v string) *HotelUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableImage(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *HotelUpdateOne) ClearImage() *HotelUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetHotelDetails sets the "hotel_details" field.
func (_u *HotelUpdateOne) SetHotelDetails(v []map[string]string) *HotelUpdateOne {
	_u.mutation.SetHotelDetails(v)
	return _u
}

// AppendHotelDetails appends value to the "hotel_details" field.
func (_u *HotelUpdateOne) AppendHotelDetails(v []map[string]string) *HotelUpdateOne {
	_u.mutation.AppendHotelDetails(v)
	return _u
}

// ClearHotelDetails clears the value of the "hotel_details" field.
func (_u *HotelUpdateOne) ClearHotelDetails() *HotelUpdateOne {
	_u.mutation.ClearHotelDetails()
	return _u
}

// SetURL sets the "url" field.
func (_u *HotelUpdateOne) SetURL(v string) *HotelUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableURL(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *HotelUpdateOne) ClearURL() *HotelUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetPid sets the "pid" field.
func (_u *HotelUpdateOne) SetPid(v string) *HotelUpdateOne {
	_u.mutation.SetPid(v)
	return _u
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillablePid(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetPid(*v)
	}
	return _u
}

// SetStyleCode sets the "style_code" field.
func (_u *HotelUpdateOne) SetStyleCode(v string) *HotelUpdateOne {
	_u.mutation.SetStyleCode(v)
	return _u
}

// SetNillableStyleCode sets the "style_code" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableStyleCode(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetStyleCode(*v)
	}
	return _u
}

// ClearStyleCode clears the value of the "style_code" field.
func (_u *HotelUpdateOne) ClearStyleCode() *HotelUpdateOne {
	_u.mutation.ClearStyleCode()
	return _u
}

// SetCrawledAt sets the "crawled_at" field.
func (_u *HotelUpdateOne) SetCrawledAt(v time.Time) *HotelUpdateOne {
	_u.mutation.SetCrawledAt(v)
	return _u
}

// SetNillableCrawledAt sets the "crawled_at" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableCrawledAt(v *time.Time) *HotelUpdateOne {
	if v != nil {
		_u.SetCrawledAt(*v)
	}
	return _u
}

// ClearCrawledAt clears the value of the "crawled_at" field.
func (_u *HotelUpdateOne) ClearCrawledAt() *HotelUpdateOne {
	_u.mutation.ClearCrawledAt()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *HotelUpdateOne) SetEmbedding(v []float32) *HotelUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *HotelUpdateOne) AppendEmbedding(v []float32) *HotelUpdateOne {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *HotelUpdateOne) ClearEmbedding() *HotelUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetSearchKeywords sets the "search_keywords" field.
func (_u *HotelUpdateOne) SetSearchKeywords(v []string) *HotelUpdateOne {
	_u.mutation.SetSearchKeywords(v)
	return _u
}

// AppendSearchKeywords appends value to the "search_keywords" field.
func (_u *HotelUpdateOne) AppendSearchKeywords(v []string) *HotelUpdateOne {
	_u.mutation.AppendSearchKeywords(v)
	return _u
}

// ClearSearchKeywords clears the value of the "search_keywords" field.
func (_u *HotelUpdateOne) ClearSearchKeywords() *HotelUpdateOne {
	_u.mutation.ClearSearchKeywords()
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *HotelUpdateOne) SetFeatured(v bool) *HotelUpdateOne {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableFeatured(v *bool) *HotelUpdateOne {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *HotelUpdateOne) SetViewCount(v int) *HotelUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableViewCount(v *int) *HotelUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *HotelUpdateOne) AddViewCount(v int) *HotelUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *HotelUpdateOne) SetClickCount(v int) *HotelUpdateOne {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableClickCount(v *int) *HotelUpdateOne {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *HotelUpdateOne) AddClickCount(v int) *HotelUpdateOne {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetPriceNumeric sets the "price_numeric" field.
func (_u *HotelUpdateOne) SetPriceNumeric(v int) *HotelUpdateOne {
	_u.mutation.ResetPriceNumeric()
	_u.mutation.SetPriceNumeric(v)
	return _u
}

// SetNillablePriceNumeric sets the "price_numeric" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillablePriceNumeric(v *int) *HotelUpdateOne {
	if v != nil {
		_u.SetPriceNumeric(*v)
	}
	return _u
}

// AddPriceNumeric adds value to the "price_numeric" field.
func (_u *HotelUpdateOne) AddPriceNumeric(v int) *HotelUpdateOne {
	_u.mutation.AddPriceNumeric(v)
	return _u
}

// ClearPriceNumeric clears the value of the "price_numeric" field.
func (_u *HotelUpdateOne) ClearPriceNumeric() *HotelUpdateOne {
	_u.mutation.ClearPriceNumeric()
	return _u
}

// SetRatingNumeric sets the "rating_numeric" field.
func (_u *HotelUpdateOne) SetRatingNumeric(v float64) *HotelUpdateOne {
	_u.mutation.ResetRatingNumeric()
	_u.mutation.SetRatingNumeric(v)
	return _u
}

// SetNillableRatingNumeric sets the "rating_numeric" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableRatingNumeric(v *float64) *HotelUpdateOne {
	if v != nil {
		_u.SetRatingNumeric(*v)
	}
	return _u
}

// AddRatingNumeric adds value to the "rating_numeric" field.
func (_u *HotelUpdateOne) AddRatingNumeric(v float64) *HotelUpdateOne {
	_u.mutation.AddRatingNumeric(v)
	return _u
}

// ClearRatingNumeric clears the value of the "rating_numeric" field.
func (_u *HotelUpdateOne) ClearRatingNumeric() *HotelUpdateOne {
	_u.mutation.ClearRatingNumeric()
	return _u
}

// Mutation returns the HotelMutation object of the builder.
func (_u *HotelUpdateOne) Mutation() *HotelMutation {
	return _u.mutation
}

// Where appends a list predicates to the HotelUpdate builder.
func (_u *HotelUpdateOne) Where(ps ...predicate.Hotel) *HotelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HotelUpdateOne) Select(field string, fields ...string) *HotelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Hotel entity.
func (_u *HotelUpdateOne) Save(ctx context.Context) (*Hotel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotelUpdateOne) SaveX(ctx context.Context) *Hotel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HotelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HotelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := hotel.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HotelUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := hotel.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Hotel.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Brand(); ok {
		if err := hotel.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Hotel.brand": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := hotel.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Hotel.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubCategory(); ok {
		if err := hotel.SubCategoryValidator(v); err != nil {
			return &ValidationError{Name: "sub_category", err: fmt.Errorf(`ent: validator failed for field "Hotel.sub_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := hotel.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Hotel.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceNumeric(); ok {
		if err := hotel.PriceNumericValidator(v); err != nil {
			return &ValidationError{Name: "price_numeric", err: fmt.Errorf(`ent: validator failed for field "Hotel.price_numeric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RatingNumeric(); ok {
		if err := hotel.RatingNumericValidator(v); err != nil {
			return &ValidationError{Name: "rating_numeric", err: fmt.Errorf(`ent: validator failed for field "Hotel.rating_numeric": %w`, err)}
		}
	}
	return nil
}

func (_u *HotelUpdateOne) sqlSave(ctx context.Context) (_node *Hotel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hotel.Table, hotel.Columns, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hotel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hotel.FieldID)
		for _, f := range fields {
			if !hotel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hotel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(hotel.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OriginalID(); ok {
		_spec.SetField(hotel.FieldOriginalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(hotel.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(hotel.FieldBrand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(hotel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(hotel.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ActualPrice(); ok {
		_spec.SetField(hotel.FieldActualPrice, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedActualPrice(); ok {
		_spec.AddField(hotel.FieldActualPrice, field.TypeFloat32, value)
	}
	if _u.mutation.ActualPriceCleared() {
		_spec.ClearField(hotel.FieldActualPrice, field.TypeFloat32)
	}
	if value, ok := _u.mutation.SellingPrice(); ok {
		_spec.SetField(hotel.FieldSellingPrice, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedSellingPrice(); ok {
		_spec.AddField(hotel.FieldSellingPrice, field.TypeFloat32, value)
	}
	if _u.mutation.SellingPriceCleared() {
		_spec.ClearField(hotel.FieldSellingPrice, field.TypeFloat32)
	}
	if value, ok := _u.mutation.Discount(); ok {
		_spec.SetField(hotel.FieldDiscount, field.TypeString, value)
	}
	if _u.mutation.DiscountCleared() {
		_spec.ClearField(hotel.FieldDiscount, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(hotel.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubCategory(); ok {
		_spec.SetField(hotel.FieldSubCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutOfStock(); ok {
		_spec.SetField(hotel.FieldOutOfStock, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Seller(); ok {
		_spec.SetField(hotel.FieldSeller, field.TypeString, value)
	}
	if _u.mutation.SellerCleared() {
		_spec.ClearField(hotel.FieldSeller, field.TypeString)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(hotel.FieldAverageRating, field.TypeString, value)
	}
	if _u.mutation.AverageRatingCleared() {
		_spec.ClearField(hotel.FieldAverageRating, field.TypeString)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(hotel.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(hotel.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.HotelDetails(); ok {
		_spec.SetField(hotel.FieldHotelDetails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHotelDetails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldHotelDetails, value)
		})
	}
	if _u.mutation.HotelDetailsCleared() {
		_spec.ClearField(hotel.FieldHotelDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(hotel.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(hotel.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Pid(); ok {
		_spec.SetField(hotel.FieldPid, field.TypeString, value)
	}
	if value, ok := _u.mutation.StyleCode(); ok {
		_spec.SetField(hotel.FieldStyleCode, field.TypeString, value)
	}
	if _u.mutation.StyleCodeCleared() {
		_spec.ClearField(hotel.FieldStyleCode, field.TypeString)
	}
	if value, ok := _u.mutation.CrawledAt(); ok {
		_spec.SetField(hotel.FieldCrawledAt, field.TypeTime, value)
	}
	if _u.mutation.CrawledAtCleared() {
		_spec.ClearField(hotel.FieldCrawledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(hotel.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldEmbedding, value)
		})
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(hotel.FieldEmbedding, field.TypeJSON)
	}
	if value, ok := _u.mutation.SearchKeywords(); ok {
		_spec.SetField(hotel.FieldSearchKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSearchKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, hotel.FieldSearchKeywords, value)
		})
	}
	if _u.mutation.SearchKeywordsCleared() {
		_spec.ClearField(hotel.FieldSearchKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(hotel.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(hotel.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(hotel.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(hotel.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(hotel.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PriceNumeric(); ok {
		_spec.SetField(hotel.FieldPriceNumeric, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriceNumeric(); ok {
		_spec.AddField(hotel.FieldPriceNumeric, field.TypeInt, value)
	}
	if _u.mutation.PriceNumericCleared() {
		_spec.ClearField(hotel.FieldPriceNumeric, field.TypeInt)
	}
	if value, ok := _u.mutation.RatingNumeric(); ok {
		_spec.SetField(hotel.FieldRatingNumeric, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatingNumeric(); ok {
		_spec.AddField(hotel.FieldRatingNumeric, field.TypeFloat64, value)
	}
	if _u.mutation.RatingNumericCleared() {
		_spec.ClearField(hotel.FieldRatingNumeric, field.TypeFloat64)
	}
	_node = &Hotel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
