// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"trivgoo-backend/ent/hotel"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Hotel is the model entity for the Hotel schema.
type Hotel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Original _id from dataset
	OriginalID string `json:"original_id,omitempty"`
	// Hotel title
	Title string `json:"title,omitempty"`
	// Brand name
	Brand string `json:"brand,omitempty"`
	// Hotel description
	Description string `json:"description,omitempty"`
	// Original price
	ActualPrice float32 `json:"actual_price,omitempty"`
	// Discounted price
	SellingPrice float32 `json:"selling_price,omitempty"`
	// Discount percentage
	Discount string `json:"discount,omitempty"`
	// Main category
	Category string `json:"category,omitempty"`
	// Sub category
	SubCategory string `json:"sub_category,omitempty"`
	// OutOfStock holds the value of the "out_of_stock" field.
	OutOfStock bool `json:"out_of_stock,omitempty"`
	// Seller name
	Seller string `json:"seller,omitempty"`
	// Average rating
	AverageRating string `json:"average_rating,omitempty"`
	// Hotel image URLs
	Image string `json:"image,omitempty"`
	// Dynamic hotel attributes
	HotelDetails []map[string]string `json:"hotel_details,omitempty"`
	// Hotel URL
	URL string `json:"url,omitempty"`
	// Flipkart hotel ID
	Pid string `json:"pid,omitempty"`
	// Style/sku code
	StyleCode string `json:"style_code,omitempty"`
	// When the data was crawled
	CrawledAt time.Time `json:"crawled_at,omitempty"`
	// Vector embeddings for semantic search
	Embedding []float32 `json:"embedding,omitempty"`
	// Keywords for full-text search
	SearchKeywords []string `json:"search_keywords,omitempty"`
	// Featured hotel
	Featured bool `json:"featured,omitempty"`
	// Number of views
	ViewCount int `json:"view_count,omitempty"`
	// Number of clicks
	ClickCount int `json:"click_count,omitempty"`
	// Price as integer for filtering
	PriceNumeric int `json:"price_numeric,omitempty"`
	// Rating as float for sorting
	RatingNumeric float64 `json:"rating_numeric,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Hotel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hotel.FieldHotelDetails, hotel.FieldEmbedding, hotel.FieldSearchKeywords:
			values[i] = new([]byte)
		case hotel.FieldOutOfStock, hotel.FieldFeatured:
			values[i] = new(sql.NullBool)
		case hotel.FieldActualPrice, hotel.FieldSellingPrice, hotel.FieldRatingNumeric:
			values[i] = new(sql.NullFloat64)
		case hotel.FieldID, hotel.FieldViewCount, hotel.FieldClickCount, hotel.FieldPriceNumeric:
			values[i] = new(sql.NullInt64)
		case hotel.FieldOriginalID, hotel.FieldTitle, hotel.FieldBrand, hotel.FieldDescription, hotel.FieldDiscount, hotel.FieldCategory, hotel.FieldSubCategory, hotel.FieldSeller, hotel.FieldAverageRating, hotel.FieldImage, hotel.FieldURL, hotel.FieldPid, hotel.FieldStyleCode:
			values[i] = new(sql.NullString)
		case hotel.FieldCreateTime, hotel.FieldUpdateTime, hotel.FieldCrawledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Hotel fields.
func (_m *Hotel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hotel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case hotel.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case hotel.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case hotel.FieldOriginalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_id", values[i])
			} else if value.Valid {
				_m.OriginalID = value.String
			}
		case hotel.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case hotel.FieldBrand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand", values[i])
			} else if value.Valid {
				_m.Brand = value.String
			}
		case hotel.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case hotel.FieldActualPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_price", values[i])
			} else if value.Valid {
				_m.ActualPrice = float32(value.Float64)
			}
		case hotel.FieldSellingPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field selling_price", values[i])
			} else if value.Valid {
				_m.SellingPrice = float32(value.Float64)
			}
		case hotel.FieldDiscount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discount", values[i])
			} else if value.Valid {
				_m.Discount = value.String
			}
		case hotel.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case hotel.FieldSubCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sub_category", values[i])
			} else if value.Valid {
				_m.SubCategory = value.String
			}
		case hotel.FieldOutOfStock:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field out_of_stock", values[i])
			} else if value.Valid {
				_m.OutOfStock = value.Bool
			}
		case hotel.FieldSeller:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seller", values[i])
			} else if value.Valid {
				_m.Seller = value.String
			}
		case hotel.FieldAverageRating:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field average_rating", values[i])
			} else if value.Valid {
				_m.AverageRating = value.String
			}
		case hotel.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		case hotel.FieldHotelDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field hotel_details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.HotelDetails); err != nil {
					return fmt.Errorf("unmarshal field hotel_details: %w", err)
				}
			}
		case hotel.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case hotel.FieldPid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pid", values[i])
			} else if value.Valid {
				_m.Pid = value.String
			}
		case hotel.FieldStyleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field style_code", values[i])
			} else if value.Valid {
				_m.StyleCode = value.String
			}
		case hotel.FieldCrawledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field crawled_at", values[i])
			} else if value.Valid {
				_m.CrawledAt = value.Time
			}
		case hotel.FieldEmbedding:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field embedding", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Embedding); err != nil {
					return fmt.Errorf("unmarshal field embedding: %w", err)
				}
			}
		case hotel.FieldSearchKeywords:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field search_keywords", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SearchKeywords); err != nil {
					return fmt.Errorf("unmarshal field search_keywords: %w", err)
				}
			}
		case hotel.FieldFeatured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field featured", values[i])
			} else if value.Valid {
				_m.Featured = value.Bool
			}
		case hotel.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				_m.ViewCount = int(value.Int64)
			}
		case hotel.FieldClickCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field click_count", values[i])
			} else if value.Valid {
				_m.ClickCount = int(value.Int64)
			}
		case hotel.FieldPriceNumeric:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_numeric", values[i])
			} else if value.Valid {
				_m.PriceNumeric = int(value.Int64)
			}
		case hotel.FieldRatingNumeric:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rating_numeric", values[i])
			} else if value.Valid {
				_m.RatingNumeric = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Hotel.
// This includes values selected through modifiers, order, etc.
func (_m *Hotel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Hotel.
// Note that you need to call Hotel.Unwrap() before calling this method if this Hotel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Hotel) Update() *HotelUpdateOne {
	return NewHotelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Hotel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Hotel) Unwrap() *Hotel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Hotel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Hotel) String() string {
	var builder strings.Builder
	builder.WriteString("Hotel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("original_id=")
	builder.WriteString(_m.OriginalID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("brand=")
	builder.WriteString(_m.Brand)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("actual_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualPrice))
	builder.WriteString(", ")
	builder.WriteString("selling_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.SellingPrice))
	builder.WriteString(", ")
	builder.WriteString("discount=")
	builder.WriteString(_m.Discount)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("sub_category=")
	builder.WriteString(_m.SubCategory)
	builder.WriteString(", ")
	builder.WriteString("out_of_stock=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutOfStock))
	builder.WriteString(", ")
	builder.WriteString("seller=")
	builder.WriteString(_m.Seller)
	builder.WriteString(", ")
	builder.WriteString("average_rating=")
	builder.WriteString(_m.AverageRating)
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteString(", ")
	builder.WriteString("hotel_details=")
	builder.WriteString(fmt.Sprintf("%v", _m.HotelDetails))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("pid=")
	builder.WriteString(_m.Pid)
	builder.WriteString(", ")
	builder.WriteString("style_code=")
	builder.WriteString(_m.StyleCode)
	builder.WriteString(", ")
	builder.WriteString("crawled_at=")
	builder.WriteString(_m.CrawledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("embedding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Embedding))
	builder.WriteString(", ")
	builder.WriteString("search_keywords=")
	builder.WriteString(fmt.Sprintf("%v", _m.SearchKeywords))
	builder.WriteString(", ")
	builder.WriteString("featured=")
	builder.WriteString(fmt.Sprintf("%v", _m.Featured))
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewCount))
	builder.WriteString(", ")
	builder.WriteString("click_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClickCount))
	builder.WriteString(", ")
	builder.WriteString("price_numeric=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceNumeric))
	builder.WriteString(", ")
	builder.WriteString("rating_numeric=")
	builder.WriteString(fmt.Sprintf("%v", _m.RatingNumeric))
	builder.WriteByte(')')
	return builder.String()
}

// Hotels is a parsable slice of Hotel.
type Hotels []*Hotel
