// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"
	"yinni_travel_backend/ent/hotel"
	"yinni_travel_backend/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHotel = "Hotel"
)

// HotelMutation represents an operation that mutates the Hotel nodes in the graph.
type HotelMutation struct {
	config
	op                    Op
	typ                   string
	id                    *int
	create_time           *time.Time
	update_time           *time.Time
	original_id           *string
	title                 *string
	brand                 *string
	description           *string
	actual_price          *float32
	addactual_price       *float32
	selling_price         *float32
	addselling_price      *float32
	discount              *string
	category              *string
	sub_category          *string
	out_of_stock          *bool
	seller                *string
	average_rating        *string
	image                 *string
	hotel_details         *[]map[string]string
	appendhotel_details   []map[string]string
	url                   *string
	pid                   *string
	style_code            *string
	crawled_at            *time.Time
	embedding             *[]float32
	appendembedding       []float32
	search_keywords       *[]string
	appendsearch_keywords []string
	featured              *bool
	view_count            *int
	addview_count         *int
	click_count           *int
	addclick_count        *int
	price_numeric         *int
	addprice_numeric      *int
	rating_numeric        *float64
	addrating_numeric     *float64
	clearedFields         map[string]struct{}
	done                  bool
	oldValue              func(context.Context) (*Hotel, error)
	predicates            []predicate.Hotel
}

var _ ent.Mutation = (*HotelMutation)(nil)

// hotelOption allows management of the mutation configuration using functional options.
type hotelOption func(*HotelMutation)

// newHotelMutation creates new mutation for the Hotel entity.
func newHotelMutation(c config, op Op, opts ...hotelOption) *HotelMutation {
	m := &HotelMutation{
		config:        c,
		op:            op,
		typ:           TypeHotel,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHotelID sets the ID field of the mutation.
func withHotelID(id int) hotelOption {
	return func(m *HotelMutation) {
		var (
			err   error
			once  sync.Once
			value *Hotel
		)
		m.oldValue = func(ctx context.Context) (*Hotel, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Hotel.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHotel sets the old Hotel of the mutation.
func withHotel(node *Hotel) hotelOption {
	return func(m *HotelMutation) {
		m.oldValue = func(context.Context) (*Hotel, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HotelMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HotelMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HotelMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HotelMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Hotel.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *HotelMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *HotelMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *HotelMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *HotelMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *HotelMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *HotelMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetOriginalID sets the "original_id" field.
func (m *HotelMutation) SetOriginalID(s string) {
	m.original_id = &s
}

// OriginalID returns the value of the "original_id" field in the mutation.
func (m *HotelMutation) OriginalID() (r string, exists bool) {
	v := m.original_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOriginalID returns the old "original_id" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldOriginalID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOriginalID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOriginalID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOriginalID: %w", err)
	}
	return oldValue.OriginalID, nil
}

// ResetOriginalID resets all changes to the "original_id" field.
func (m *HotelMutation) ResetOriginalID() {
	m.original_id = nil
}

// SetTitle sets the "title" field.
func (m *HotelMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *HotelMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *HotelMutation) ResetTitle() {
	m.title = nil
}

// SetBrand sets the "brand" field.
func (m *HotelMutation) SetBrand(s string) {
	m.brand = &s
}

// Brand returns the value of the "brand" field in the mutation.
func (m *HotelMutation) Brand() (r string, exists bool) {
	v := m.brand
	if v == nil {
		return
	}
	return *v, true
}

// OldBrand returns the old "brand" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldBrand(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBrand is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBrand requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBrand: %w", err)
	}
	return oldValue.Brand, nil
}

// ResetBrand resets all changes to the "brand" field.
func (m *HotelMutation) ResetBrand() {
	m.brand = nil
}

// SetDescription sets the "description" field.
func (m *HotelMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *HotelMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *HotelMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[hotel.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *HotelMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[hotel.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *HotelMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, hotel.FieldDescription)
}

// SetActualPrice sets the "actual_price" field.
func (m *HotelMutation) SetActualPrice(f float32) {
	m.actual_price = &f
	m.addactual_price = nil
}

// ActualPrice returns the value of the "actual_price" field in the mutation.
func (m *HotelMutation) ActualPrice() (r float32, exists bool) {
	v := m.actual_price
	if v == nil {
		return
	}
	return *v, true
}

// OldActualPrice returns the old "actual_price" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldActualPrice(ctx context.Context) (v float32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActualPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActualPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActualPrice: %w", err)
	}
	return oldValue.ActualPrice, nil
}

// AddActualPrice adds f to the "actual_price" field.
func (m *HotelMutation) AddActualPrice(f float32) {
	if m.addactual_price != nil {
		*m.addactual_price += f
	} else {
		m.addactual_price = &f
	}
}

// AddedActualPrice returns the value that was added to the "actual_price" field in this mutation.
func (m *HotelMutation) AddedActualPrice() (r float32, exists bool) {
	v := m.addactual_price
	if v == nil {
		return
	}
	return *v, true
}

// ClearActualPrice clears the value of the "actual_price" field.
func (m *HotelMutation) ClearActualPrice() {
	m.actual_price = nil
	m.addactual_price = nil
	m.clearedFields[hotel.FieldActualPrice] = struct{}{}
}

// ActualPriceCleared returns if the "actual_price" field was cleared in this mutation.
func (m *HotelMutation) ActualPriceCleared() bool {
	_, ok := m.clearedFields[hotel.FieldActualPrice]
	return ok
}

// ResetActualPrice resets all changes to the "actual_price" field.
func (m *HotelMutation) ResetActualPrice() {
	m.actual_price = nil
	m.addactual_price = nil
	delete(m.clearedFields, hotel.FieldActualPrice)
}

// SetSellingPrice sets the "selling_price" field.
func (m *HotelMutation) SetSellingPrice(f float32) {
	m.selling_price = &f
	m.addselling_price = nil
}

// SellingPrice returns the value of the "selling_price" field in the mutation.
func (m *HotelMutation) SellingPrice() (r float32, exists bool) {
	v := m.selling_price
	if v == nil {
		return
	}
	return *v, true
}

// OldSellingPrice returns the old "selling_price" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldSellingPrice(ctx context.Context) (v float32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSellingPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSellingPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSellingPrice: %w", err)
	}
	return oldValue.SellingPrice, nil
}

// AddSellingPrice adds f to the "selling_price" field.
func (m *HotelMutation) AddSellingPrice(f float32) {
	if m.addselling_price != nil {
		*m.addselling_price += f
	} else {
		m.addselling_price = &f
	}
}

// AddedSellingPrice returns the value that was added to the "selling_price" field in this mutation.
func (m *HotelMutation) AddedSellingPrice() (r float32, exists bool) {
	v := m.addselling_price
	if v == nil {
		return
	}
	return *v, true
}

// ClearSellingPrice clears the value of the "selling_price" field.
func (m *HotelMutation) ClearSellingPrice() {
	m.selling_price = nil
	m.addselling_price = nil
	m.clearedFields[hotel.FieldSellingPrice] = struct{}{}
}

// SellingPriceCleared returns if the "selling_price" field was cleared in this mutation.
func (m *HotelMutation) SellingPriceCleared() bool {
	_, ok := m.clearedFields[hotel.FieldSellingPrice]
	return ok
}

// ResetSellingPrice resets all changes to the "selling_price" field.
func (m *HotelMutation) ResetSellingPrice() {
	m.selling_price = nil
	m.addselling_price = nil
	delete(m.clearedFields, hotel.FieldSellingPrice)
}

// SetDiscount sets the "discount" field.
func (m *HotelMutation) SetDiscount(s string) {
	m.discount = &s
}

// Discount returns the value of the "discount" field in the mutation.
func (m *HotelMutation) Discount() (r string, exists bool) {
	v := m.discount
	if v == nil {
		return
	}
	return *v, true
}

// OldDiscount returns the old "discount" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldDiscount(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDiscount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDiscount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDiscount: %w", err)
	}
	return oldValue.Discount, nil
}

// ClearDiscount clears the value of the "discount" field.
func (m *HotelMutation) ClearDiscount() {
	m.discount = nil
	m.clearedFields[hotel.FieldDiscount] = struct{}{}
}

// DiscountCleared returns if the "discount" field was cleared in this mutation.
func (m *HotelMutation) DiscountCleared() bool {
	_, ok := m.clearedFields[hotel.FieldDiscount]
	return ok
}

// ResetDiscount resets all changes to the "discount" field.
func (m *HotelMutation) ResetDiscount() {
	m.discount = nil
	delete(m.clearedFields, hotel.FieldDiscount)
}

// SetCategory sets the "category" field.
func (m *HotelMutation) SetCategory(s string) {
	m.category = &s
}

// Category returns the value of the "category" field in the mutation.
func (m *HotelMutation) Category() (r string, exists bool) {
	v := m.category
	if v == nil {
		return
	}
	return *v, true
}

// OldCategory returns the old "category" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldCategory(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCategory is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCategory requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCategory: %w", err)
	}
	return oldValue.Category, nil
}

// ResetCategory resets all changes to the "category" field.
func (m *HotelMutation) ResetCategory() {
	m.category = nil
}

// SetSubCategory sets the "sub_category" field.
func (m *HotelMutation) SetSubCategory(s string) {
	m.sub_category = &s
}

// SubCategory returns the value of the "sub_category" field in the mutation.
func (m *HotelMutation) SubCategory() (r string, exists bool) {
	v := m.sub_category
	if v == nil {
		return
	}
	return *v, true
}

// OldSubCategory returns the old "sub_category" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldSubCategory(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubCategory is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubCategory requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubCategory: %w", err)
	}
	return oldValue.SubCategory, nil
}

// ResetSubCategory resets all changes to the "sub_category" field.
func (m *HotelMutation) ResetSubCategory() {
	m.sub_category = nil
}

// SetOutOfStock sets the "out_of_stock" field.
func (m *HotelMutation) SetOutOfStock(b bool) {
	m.out_of_stock = &b
}

// OutOfStock returns the value of the "out_of_stock" field in the mutation.
func (m *HotelMutation) OutOfStock() (r bool, exists bool) {
	v := m.out_of_stock
	if v == nil {
		return
	}
	return *v, true
}

// OldOutOfStock returns the old "out_of_stock" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldOutOfStock(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOutOfStock is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOutOfStock requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOutOfStock: %w", err)
	}
	return oldValue.OutOfStock, nil
}

// ResetOutOfStock resets all changes to the "out_of_stock" field.
func (m *HotelMutation) ResetOutOfStock() {
	m.out_of_stock = nil
}

// SetSeller sets the "seller" field.
func (m *HotelMutation) SetSeller(s string) {
	m.seller = &s
}

// Seller returns the value of the "seller" field in the mutation.
func (m *HotelMutation) Seller() (r string, exists bool) {
	v := m.seller
	if v == nil {
		return
	}
	return *v, true
}

// OldSeller returns the old "seller" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldSeller(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeller is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeller requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeller: %w", err)
	}
	return oldValue.Seller, nil
}

// ClearSeller clears the value of the "seller" field.
func (m *HotelMutation) ClearSeller() {
	m.seller = nil
	m.clearedFields[hotel.FieldSeller] = struct{}{}
}

// SellerCleared returns if the "seller" field was cleared in this mutation.
func (m *HotelMutation) SellerCleared() bool {
	_, ok := m.clearedFields[hotel.FieldSeller]
	return ok
}

// ResetSeller resets all changes to the "seller" field.
func (m *HotelMutation) ResetSeller() {
	m.seller = nil
	delete(m.clearedFields, hotel.FieldSeller)
}

// SetAverageRating sets the "average_rating" field.
func (m *HotelMutation) SetAverageRating(s string) {
	m.average_rating = &s
}

// AverageRating returns the value of the "average_rating" field in the mutation.
func (m *HotelMutation) AverageRating() (r string, exists bool) {
	v := m.average_rating
	if v == nil {
		return
	}
	return *v, true
}

// OldAverageRating returns the old "average_rating" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldAverageRating(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAverageRating is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAverageRating requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAverageRating: %w", err)
	}
	return oldValue.AverageRating, nil
}

// ClearAverageRating clears the value of the "average_rating" field.
func (m *HotelMutation) ClearAverageRating() {
	m.average_rating = nil
	m.clearedFields[hotel.FieldAverageRating] = struct{}{}
}

// AverageRatingCleared returns if the "average_rating" field was cleared in this mutation.
func (m *HotelMutation) AverageRatingCleared() bool {
	_, ok := m.clearedFields[hotel.FieldAverageRating]
	return ok
}

// ResetAverageRating resets all changes to the "average_rating" field.
func (m *HotelMutation) ResetAverageRating() {
	m.average_rating = nil
	delete(m.clearedFields, hotel.FieldAverageRating)
}

// SetImage sets the "image" field.
func (m *HotelMutation) SetImage(s string) {
	m.image = &s
}

// Image returns the value of the "image" field in the mutation.
func (m *HotelMutation) Image() (r string, exists bool) {
	v := m.image
	if v == nil {
		return
	}
	return *v, true
}

// OldImage returns the old "image" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImage: %w", err)
	}
	return oldValue.Image, nil
}

// ClearImage clears the value of the "image" field.
func (m *HotelMutation) ClearImage() {
	m.image = nil
	m.clearedFields[hotel.FieldImage] = struct{}{}
}

// ImageCleared returns if the "image" field was cleared in this mutation.
func (m *HotelMutation) ImageCleared() bool {
	_, ok := m.clearedFields[hotel.FieldImage]
	return ok
}

// ResetImage resets all changes to the "image" field.
func (m *HotelMutation) ResetImage() {
	m.image = nil
	delete(m.clearedFields, hotel.FieldImage)
}

// SetHotelDetails sets the "hotel_details" field.
func (m *HotelMutation) SetHotelDetails(value []map[string]string) {
	m.hotel_details = &value
	m.appendhotel_details = nil
}

// HotelDetails returns the value of the "hotel_details" field in the mutation.
func (m *HotelMutation) HotelDetails() (r []map[string]string, exists bool) {
	v := m.hotel_details
	if v == nil {
		return
	}
	return *v, true
}

// OldHotelDetails returns the old "hotel_details" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldHotelDetails(ctx context.Context) (v []map[string]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHotelDetails is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHotelDetails requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHotelDetails: %w", err)
	}
	return oldValue.HotelDetails, nil
}

// AppendHotelDetails adds value to the "hotel_details" field.
func (m *HotelMutation) AppendHotelDetails(value []map[string]string) {
	m.appendhotel_details = append(m.appendhotel_details, value...)
}

// AppendedHotelDetails returns the list of values that were appended to the "hotel_details" field in this mutation.
func (m *HotelMutation) AppendedHotelDetails() ([]map[string]string, bool) {
	if len(m.appendhotel_details) == 0 {
		return nil, false
	}
	return m.appendhotel_details, true
}

// ClearHotelDetails clears the value of the "hotel_details" field.
func (m *HotelMutation) ClearHotelDetails() {
	m.hotel_details = nil
	m.appendhotel_details = nil
	m.clearedFields[hotel.FieldHotelDetails] = struct{}{}
}

// HotelDetailsCleared returns if the "hotel_details" field was cleared in this mutation.
func (m *HotelMutation) HotelDetailsCleared() bool {
	_, ok := m.clearedFields[hotel.FieldHotelDetails]
	return ok
}

// ResetHotelDetails resets all changes to the "hotel_details" field.
func (m *HotelMutation) ResetHotelDetails() {
	m.hotel_details = nil
	m.appendhotel_details = nil
	delete(m.clearedFields, hotel.FieldHotelDetails)
}

// SetURL sets the "url" field.
func (m *HotelMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *HotelMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ClearURL clears the value of the "url" field.
func (m *HotelMutation) ClearURL() {
	m.url = nil
	m.clearedFields[hotel.FieldURL] = struct{}{}
}

// URLCleared returns if the "url" field was cleared in this mutation.
func (m *HotelMutation) URLCleared() bool {
	_, ok := m.clearedFields[hotel.FieldURL]
	return ok
}

// ResetURL resets all changes to the "url" field.
func (m *HotelMutation) ResetURL() {
	m.url = nil
	delete(m.clearedFields, hotel.FieldURL)
}

// SetPid sets the "pid" field.
func (m *HotelMutation) SetPid(s string) {
	m.pid = &s
}

// Pid returns the value of the "pid" field in the mutation.
func (m *HotelMutation) Pid() (r string, exists bool) {
	v := m.pid
	if v == nil {
		return
	}
	return *v, true
}

// OldPid returns the old "pid" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldPid(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPid: %w", err)
	}
	return oldValue.Pid, nil
}

// ResetPid resets all changes to the "pid" field.
func (m *HotelMutation) ResetPid() {
	m.pid = nil
}

// SetStyleCode sets the "style_code" field.
func (m *HotelMutation) SetStyleCode(s string) {
	m.style_code = &s
}

// StyleCode returns the value of the "style_code" field in the mutation.
func (m *HotelMutation) StyleCode() (r string, exists bool) {
	v := m.style_code
	if v == nil {
		return
	}
	return *v, true
}

// OldStyleCode returns the old "style_code" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldStyleCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStyleCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStyleCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStyleCode: %w", err)
	}
	return oldValue.StyleCode, nil
}

// ClearStyleCode clears the value of the "style_code" field.
func (m *HotelMutation) ClearStyleCode() {
	m.style_code = nil
	m.clearedFields[hotel.FieldStyleCode] = struct{}{}
}

// StyleCodeCleared returns if the "style_code" field was cleared in this mutation.
func (m *HotelMutation) StyleCodeCleared() bool {
	_, ok := m.clearedFields[hotel.FieldStyleCode]
	return ok
}

// ResetStyleCode resets all changes to the "style_code" field.
func (m *HotelMutation) ResetStyleCode() {
	m.style_code = nil
	delete(m.clearedFields, hotel.FieldStyleCode)
}

// SetCrawledAt sets the "crawled_at" field.
func (m *HotelMutation) SetCrawledAt(t time.Time) {
	m.crawled_at = &t
}

// CrawledAt returns the value of the "crawled_at" field in the mutation.
func (m *HotelMutation) CrawledAt() (r time.Time, exists bool) {
	v := m.crawled_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCrawledAt returns the old "crawled_at" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldCrawledAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCrawledAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCrawledAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCrawledAt: %w", err)
	}
	return oldValue.CrawledAt, nil
}

// ClearCrawledAt clears the value of the "crawled_at" field.
func (m *HotelMutation) ClearCrawledAt() {
	m.crawled_at = nil
	m.clearedFields[hotel.FieldCrawledAt] = struct{}{}
}

// CrawledAtCleared returns if the "crawled_at" field was cleared in this mutation.
func (m *HotelMutation) CrawledAtCleared() bool {
	_, ok := m.clearedFields[hotel.FieldCrawledAt]
	return ok
}

// ResetCrawledAt resets all changes to the "crawled_at" field.
func (m *HotelMutation) ResetCrawledAt() {
	m.crawled_at = nil
	delete(m.clearedFields, hotel.FieldCrawledAt)
}

// SetEmbedding sets the "embedding" field.
func (m *HotelMutation) SetEmbedding(f []float32) {
	m.embedding = &f
	m.appendembedding = nil
}

// Embedding returns the value of the "embedding" field in the mutation.
func (m *HotelMutation) Embedding() (r []float32, exists bool) {
	v := m.embedding
	if v == nil {
		return
	}
	return *v, true
}

// OldEmbedding returns the old "embedding" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldEmbedding(ctx context.Context) (v []float32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmbedding is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmbedding requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmbedding: %w", err)
	}
	return oldValue.Embedding, nil
}

// AppendEmbedding adds f to the "embedding" field.
func (m *HotelMutation) AppendEmbedding(f []float32) {
	m.appendembedding = append(m.appendembedding, f...)
}

// AppendedEmbedding returns the list of values that were appended to the "embedding" field in this mutation.
func (m *HotelMutation) AppendedEmbedding() ([]float32, bool) {
	if len(m.appendembedding) == 0 {
		return nil, false
	}
	return m.appendembedding, true
}

// ClearEmbedding clears the value of the "embedding" field.
func (m *HotelMutation) ClearEmbedding() {
	m.embedding = nil
	m.appendembedding = nil
	m.clearedFields[hotel.FieldEmbedding] = struct{}{}
}

// EmbeddingCleared returns if the "embedding" field was cleared in this mutation.
func (m *HotelMutation) EmbeddingCleared() bool {
	_, ok := m.clearedFields[hotel.FieldEmbedding]
	return ok
}

// ResetEmbedding resets all changes to the "embedding" field.
func (m *HotelMutation) ResetEmbedding() {
	m.embedding = nil
	m.appendembedding = nil
	delete(m.clearedFields, hotel.FieldEmbedding)
}

// SetSearchKeywords sets the "search_keywords" field.
func (m *HotelMutation) SetSearchKeywords(s []string) {
	m.search_keywords = &s
	m.appendsearch_keywords = nil
}

// SearchKeywords returns the value of the "search_keywords" field in the mutation.
func (m *HotelMutation) SearchKeywords() (r []string, exists bool) {
	v := m.search_keywords
	if v == nil {
		return
	}
	return *v, true
}

// OldSearchKeywords returns the old "search_keywords" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldSearchKeywords(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSearchKeywords is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSearchKeywords requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSearchKeywords: %w", err)
	}
	return oldValue.SearchKeywords, nil
}

// AppendSearchKeywords adds s to the "search_keywords" field.
func (m *HotelMutation) AppendSearchKeywords(s []string) {
	m.appendsearch_keywords = append(m.appendsearch_keywords, s...)
}

// AppendedSearchKeywords returns the list of values that were appended to the "search_keywords" field in this mutation.
func (m *HotelMutation) AppendedSearchKeywords() ([]string, bool) {
	if len(m.appendsearch_keywords) == 0 {
		return nil, false
	}
	return m.appendsearch_keywords, true
}

// ClearSearchKeywords clears the value of the "search_keywords" field.
func (m *HotelMutation) ClearSearchKeywords() {
	m.search_keywords = nil
	m.appendsearch_keywords = nil
	m.clearedFields[hotel.FieldSearchKeywords] = struct{}{}
}

// SearchKeywordsCleared returns if the "search_keywords" field was cleared in this mutation.
func (m *HotelMutation) SearchKeywordsCleared() bool {
	_, ok := m.clearedFields[hotel.FieldSearchKeywords]
	return ok
}

// ResetSearchKeywords resets all changes to the "search_keywords" field.
func (m *HotelMutation) ResetSearchKeywords() {
	m.search_keywords = nil
	m.appendsearch_keywords = nil
	delete(m.clearedFields, hotel.FieldSearchKeywords)
}

// SetFeatured sets the "featured" field.
func (m *HotelMutation) SetFeatured(b bool) {
	m.featured = &b
}

// Featured returns the value of the "featured" field in the mutation.
func (m *HotelMutation) Featured() (r bool, exists bool) {
	v := m.featured
	if v == nil {
		return
	}
	return *v, true
}

// OldFeatured returns the old "featured" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldFeatured(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFeatured is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFeatured requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFeatured: %w", err)
	}
	return oldValue.Featured, nil
}

// ResetFeatured resets all changes to the "featured" field.
func (m *HotelMutation) ResetFeatured() {
	m.featured = nil
}

// SetViewCount sets the "view_count" field.
func (m *HotelMutation) SetViewCount(i int) {
	m.view_count = &i
	m.addview_count = nil
}

// ViewCount returns the value of the "view_count" field in the mutation.
func (m *HotelMutation) ViewCount() (r int, exists bool) {
	v := m.view_count
	if v == nil {
		return
	}
	return *v, true
}

// OldViewCount returns the old "view_count" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldViewCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldViewCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldViewCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldViewCount: %w", err)
	}
	return oldValue.ViewCount, nil
}

// AddViewCount adds i to the "view_count" field.
func (m *HotelMutation) AddViewCount(i int) {
	if m.addview_count != nil {
		*m.addview_count += i
	} else {
		m.addview_count = &i
	}
}

// AddedViewCount returns the value that was added to the "view_count" field in this mutation.
func (m *HotelMutation) AddedViewCount() (r int, exists bool) {
	v := m.addview_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetViewCount resets all changes to the "view_count" field.
func (m *HotelMutation) ResetViewCount() {
	m.view_count = nil
	m.addview_count = nil
}

// SetClickCount sets the "click_count" field.
func (m *HotelMutation) SetClickCount(i int) {
	m.click_count = &i
	m.addclick_count = nil
}

// ClickCount returns the value of the "click_count" field in the mutation.
func (m *HotelMutation) ClickCount() (r int, exists bool) {
	v := m.click_count
	if v == nil {
		return
	}
	return *v, true
}

// OldClickCount returns the old "click_count" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldClickCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClickCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClickCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClickCount: %w", err)
	}
	return oldValue.ClickCount, nil
}

// AddClickCount adds i to the "click_count" field.
func (m *HotelMutation) AddClickCount(i int) {
	if m.addclick_count != nil {
		*m.addclick_count += i
	} else {
		m.addclick_count = &i
	}
}

// AddedClickCount returns the value that was added to the "click_count" field in this mutation.
func (m *HotelMutation) AddedClickCount() (r int, exists bool) {
	v := m.addclick_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetClickCount resets all changes to the "click_count" field.
func (m *HotelMutation) ResetClickCount() {
	m.click_count = nil
	m.addclick_count = nil
}

// SetPriceNumeric sets the "price_numeric" field.
func (m *HotelMutation) SetPriceNumeric(i int) {
	m.price_numeric = &i
	m.addprice_numeric = nil
}

// PriceNumeric returns the value of the "price_numeric" field in the mutation.
func (m *HotelMutation) PriceNumeric() (r int, exists bool) {
	v := m.price_numeric
	if v == nil {
		return
	}
	return *v, true
}

// OldPriceNumeric returns the old "price_numeric" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldPriceNumeric(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPriceNumeric is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPriceNumeric requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPriceNumeric: %w", err)
	}
	return oldValue.PriceNumeric, nil
}

// AddPriceNumeric adds i to the "price_numeric" field.
func (m *HotelMutation) AddPriceNumeric(i int) {
	if m.addprice_numeric != nil {
		*m.addprice_numeric += i
	} else {
		m.addprice_numeric = &i
	}
}

// AddedPriceNumeric returns the value that was added to the "price_numeric" field in this mutation.
func (m *HotelMutation) AddedPriceNumeric() (r int, exists bool) {
	v := m.addprice_numeric
	if v == nil {
		return
	}
	return *v, true
}

// ClearPriceNumeric clears the value of the "price_numeric" field.
func (m *HotelMutation) ClearPriceNumeric() {
	m.price_numeric = nil
	m.addprice_numeric = nil
	m.clearedFields[hotel.FieldPriceNumeric] = struct{}{}
}

// PriceNumericCleared returns if the "price_numeric" field was cleared in this mutation.
func (m *HotelMutation) PriceNumericCleared() bool {
	_, ok := m.clearedFields[hotel.FieldPriceNumeric]
	return ok
}

// ResetPriceNumeric resets all changes to the "price_numeric" field.
func (m *HotelMutation) ResetPriceNumeric() {
	m.price_numeric = nil
	m.addprice_numeric = nil
	delete(m.clearedFields, hotel.FieldPriceNumeric)
}

// SetRatingNumeric sets the "rating_numeric" field.
func (m *HotelMutation) SetRatingNumeric(f float64) {
	m.rating_numeric = &f
	m.addrating_numeric = nil
}

// RatingNumeric returns the value of the "rating_numeric" field in the mutation.
func (m *HotelMutation) RatingNumeric() (r float64, exists bool) {
	v := m.rating_numeric
	if v == nil {
		return
	}
	return *v, true
}

// OldRatingNumeric returns the old "rating_numeric" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldRatingNumeric(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRatingNumeric is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRatingNumeric requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRatingNumeric: %w", err)
	}
	return oldValue.RatingNumeric, nil
}

// AddRatingNumeric adds f to the "rating_numeric" field.
func (m *HotelMutation) AddRatingNumeric(f float64) {
	if m.addrating_numeric != nil {
		*m.addrating_numeric += f
	} else {
		m.addrating_numeric = &f
	}
}

// AddedRatingNumeric returns the value that was added to the "rating_numeric" field in this mutation.
func (m *HotelMutation) AddedRatingNumeric() (r float64, exists bool) {
	v := m.addrating_numeric
	if v == nil {
		return
	}
	return *v, true
}

// ClearRatingNumeric clears the value of the "rating_numeric" field.
func (m *HotelMutation) ClearRatingNumeric() {
	m.rating_numeric = nil
	m.addrating_numeric = nil
	m.clearedFields[hotel.FieldRatingNumeric] = struct{}{}
}

// RatingNumericCleared returns if the "rating_numeric" field was cleared in this mutation.
func (m *HotelMutation) RatingNumericCleared() bool {
	_, ok := m.clearedFields[hotel.FieldRatingNumeric]
	return ok
}

// ResetRatingNumeric resets all changes to the "rating_numeric" field.
func (m *HotelMutation) ResetRatingNumeric() {
	m.rating_numeric = nil
	m.addrating_numeric = nil
	delete(m.clearedFields, hotel.FieldRatingNumeric)
}

// Where appends a list predicates to the HotelMutation builder.
func (m *HotelMutation) Where(ps ...predicate.Hotel) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HotelMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HotelMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Hotel, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HotelMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HotelMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Hotel).
func (m *HotelMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HotelMutation) Fields() []string {
	fields := make([]string, 0, 27)
	if m.create_time != nil {
		fields = append(fields, hotel.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, hotel.FieldUpdateTime)
	}
	if m.original_id != nil {
		fields = append(fields, hotel.FieldOriginalID)
	}
	if m.title != nil {
		fields = append(fields, hotel.FieldTitle)
	}
	if m.brand != nil {
		fields = append(fields, hotel.FieldBrand)
	}
	if m.description != nil {
		fields = append(fields, hotel.FieldDescription)
	}
	if m.actual_price != nil {
		fields = append(fields, hotel.FieldActualPrice)
	}
	if m.selling_price != nil {
		fields = append(fields, hotel.FieldSellingPrice)
	}
	if m.discount != nil {
		fields = append(fields, hotel.FieldDiscount)
	}
	if m.category != nil {
		fields = append(fields, hotel.FieldCategory)
	}
	if m.sub_category != nil {
		fields = append(fields, hotel.FieldSubCategory)
	}
	if m.out_of_stock != nil {
		fields = append(fields, hotel.FieldOutOfStock)
	}
	if m.seller != nil {
		fields = append(fields, hotel.FieldSeller)
	}
	if m.average_rating != nil {
		fields = append(fields, hotel.FieldAverageRating)
	}
	if m.image != nil {
		fields = append(fields, hotel.FieldImage)
	}
	if m.hotel_details != nil {
		fields = append(fields, hotel.FieldHotelDetails)
	}
	if m.url != nil {
		fields = append(fields, hotel.FieldURL)
	}
	if m.pid != nil {
		fields = append(fields, hotel.FieldPid)
	}
	if m.style_code != nil {
		fields = append(fields, hotel.FieldStyleCode)
	}
	if m.crawled_at != nil {
		fields = append(fields, hotel.FieldCrawledAt)
	}
	if m.embedding != nil {
		fields = append(fields, hotel.FieldEmbedding)
	}
	if m.search_keywords != nil {
		fields = append(fields, hotel.FieldSearchKeywords)
	}
	if m.featured != nil {
		fields = append(fields, hotel.FieldFeatured)
	}
	if m.view_count != nil {
		fields = append(fields, hotel.FieldViewCount)
	}
	if m.click_count != nil {
		fields = append(fields, hotel.FieldClickCount)
	}
	if m.price_numeric != nil {
		fields = append(fields, hotel.FieldPriceNumeric)
	}
	if m.rating_numeric != nil {
		fields = append(fields, hotel.FieldRatingNumeric)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HotelMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case hotel.FieldCreateTime:
		return m.CreateTime()
	case hotel.FieldUpdateTime:
		return m.UpdateTime()
	case hotel.FieldOriginalID:
		return m.OriginalID()
	case hotel.FieldTitle:
		return m.Title()
	case hotel.FieldBrand:
		return m.Brand()
	case hotel.FieldDescription:
		return m.Description()
	case hotel.FieldActualPrice:
		return m.ActualPrice()
	case hotel.FieldSellingPrice:
		return m.SellingPrice()
	case hotel.FieldDiscount:
		return m.Discount()
	case hotel.FieldCategory:
		return m.Category()
	case hotel.FieldSubCategory:
		return m.SubCategory()
	case hotel.FieldOutOfStock:
		return m.OutOfStock()
	case hotel.FieldSeller:
		return m.Seller()
	case hotel.FieldAverageRating:
		return m.AverageRating()
	case hotel.FieldImage:
		return m.Image()
	case hotel.FieldHotelDetails:
		return m.HotelDetails()
	case hotel.FieldURL:
		return m.URL()
	case hotel.FieldPid:
		return m.Pid()
	case hotel.FieldStyleCode:
		return m.StyleCode()
	case hotel.FieldCrawledAt:
		return m.CrawledAt()
	case hotel.FieldEmbedding:
		return m.Embedding()
	case hotel.FieldSearchKeywords:
		return m.SearchKeywords()
	case hotel.FieldFeatured:
		return m.Featured()
	case hotel.FieldViewCount:
		return m.ViewCount()
	case hotel.FieldClickCount:
		return m.ClickCount()
	case hotel.FieldPriceNumeric:
		return m.PriceNumeric()
	case hotel.FieldRatingNumeric:
		return m.RatingNumeric()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HotelMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case hotel.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case hotel.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case hotel.FieldOriginalID:
		return m.OldOriginalID(ctx)
	case hotel.FieldTitle:
		return m.OldTitle(ctx)
	case hotel.FieldBrand:
		return m.OldBrand(ctx)
	case hotel.FieldDescription:
		return m.OldDescription(ctx)
	case hotel.FieldActualPrice:
		return m.OldActualPrice(ctx)
	case hotel.FieldSellingPrice:
		return m.OldSellingPrice(ctx)
	case hotel.FieldDiscount:
		return m.OldDiscount(ctx)
	case hotel.FieldCategory:
		return m.OldCategory(ctx)
	case hotel.FieldSubCategory:
		return m.OldSubCategory(ctx)
	case hotel.FieldOutOfStock:
		return m.OldOutOfStock(ctx)
	case hotel.FieldSeller:
		return m.OldSeller(ctx)
	case hotel.FieldAverageRating:
		return m.OldAverageRating(ctx)
	case hotel.FieldImage:
		return m.OldImage(ctx)
	case hotel.FieldHotelDetails:
		return m.OldHotelDetails(ctx)
	case hotel.FieldURL:
		return m.OldURL(ctx)
	case hotel.FieldPid:
		return m.OldPid(ctx)
	case hotel.FieldStyleCode:
		return m.OldStyleCode(ctx)
	case hotel.FieldCrawledAt:
		return m.OldCrawledAt(ctx)
	case hotel.FieldEmbedding:
		return m.OldEmbedding(ctx)
	case hotel.FieldSearchKeywords:
		return m.OldSearchKeywords(ctx)
	case hotel.FieldFeatured:
		return m.OldFeatured(ctx)
	case hotel.FieldViewCount:
		return m.OldViewCount(ctx)
	case hotel.FieldClickCount:
		return m.OldClickCount(ctx)
	case hotel.FieldPriceNumeric:
		return m.OldPriceNumeric(ctx)
	case hotel.FieldRatingNumeric:
		return m.OldRatingNumeric(ctx)
	}
	return nil, fmt.Errorf("unknown Hotel field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HotelMutation) SetField(name string, value ent.Value) error {
	switch name {
	case hotel.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case hotel.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case hotel.FieldOriginalID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOriginalID(v)
		return nil
	case hotel.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case hotel.FieldBrand:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBrand(v)
		return nil
	case hotel.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case hotel.FieldActualPrice:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActualPrice(v)
		return nil
	case hotel.FieldSellingPrice:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSellingPrice(v)
		return nil
	case hotel.FieldDiscount:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDiscount(v)
		return nil
	case hotel.FieldCategory:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCategory(v)
		return nil
	case hotel.FieldSubCategory:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubCategory(v)
		return nil
	case hotel.FieldOutOfStock:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOutOfStock(v)
		return nil
	case hotel.FieldSeller:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeller(v)
		return nil
	case hotel.FieldAverageRating:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAverageRating(v)
		return nil
	case hotel.FieldImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImage(v)
		return nil
	case hotel.FieldHotelDetails:
		v, ok := value.([]map[string]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHotelDetails(v)
		return nil
	case hotel.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case hotel.FieldPid:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPid(v)
		return nil
	case hotel.FieldStyleCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStyleCode(v)
		return nil
	case hotel.FieldCrawledAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCrawledAt(v)
		return nil
	case hotel.FieldEmbedding:
		v, ok := value.([]float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmbedding(v)
		return nil
	case hotel.FieldSearchKeywords:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSearchKeywords(v)
		return nil
	case hotel.FieldFeatured:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFeatured(v)
		return nil
	case hotel.FieldViewCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetViewCount(v)
		return nil
	case hotel.FieldClickCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClickCount(v)
		return nil
	case hotel.FieldPriceNumeric:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPriceNumeric(v)
		return nil
	case hotel.FieldRatingNumeric:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRatingNumeric(v)
		return nil
	}
	return fmt.Errorf("unknown Hotel field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HotelMutation) AddedFields() []string {
	var fields []string
	if m.addactual_price != nil {
		fields = append(fields, hotel.FieldActualPrice)
	}
	if m.addselling_price != nil {
		fields = append(fields, hotel.FieldSellingPrice)
	}
	if m.addview_count != nil {
		fields = append(fields, hotel.FieldViewCount)
	}
	if m.addclick_count != nil {
		fields = append(fields, hotel.FieldClickCount)
	}
	if m.addprice_numeric != nil {
		fields = append(fields, hotel.FieldPriceNumeric)
	}
	if m.addrating_numeric != nil {
		fields = append(fields, hotel.FieldRatingNumeric)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HotelMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case hotel.FieldActualPrice:
		return m.AddedActualPrice()
	case hotel.FieldSellingPrice:
		return m.AddedSellingPrice()
	case hotel.FieldViewCount:
		return m.AddedViewCount()
	case hotel.FieldClickCount:
		return m.AddedClickCount()
	case hotel.FieldPriceNumeric:
		return m.AddedPriceNumeric()
	case hotel.FieldRatingNumeric:
		return m.AddedRatingNumeric()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HotelMutation) AddField(name string, value ent.Value) error {
	switch name {
	case hotel.FieldActualPrice:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddActualPrice(v)
		return nil
	case hotel.FieldSellingPrice:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSellingPrice(v)
		return nil
	case hotel.FieldViewCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddViewCount(v)
		return nil
	case hotel.FieldClickCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddClickCount(v)
		return nil
	case hotel.FieldPriceNumeric:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPriceNumeric(v)
		return nil
	case hotel.FieldRatingNumeric:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRatingNumeric(v)
		return nil
	}
	return fmt.Errorf("unknown Hotel numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HotelMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(hotel.FieldDescription) {
		fields = append(fields, hotel.FieldDescription)
	}
	if m.FieldCleared(hotel.FieldActualPrice) {
		fields = append(fields, hotel.FieldActualPrice)
	}
	if m.FieldCleared(hotel.FieldSellingPrice) {
		fields = append(fields, hotel.FieldSellingPrice)
	}
	if m.FieldCleared(hotel.FieldDiscount) {
		fields = append(fields, hotel.FieldDiscount)
	}
	if m.FieldCleared(hotel.FieldSeller) {
		fields = append(fields, hotel.FieldSeller)
	}
	if m.FieldCleared(hotel.FieldAverageRating) {
		fields = append(fields, hotel.FieldAverageRating)
	}
	if m.FieldCleared(hotel.FieldImage) {
		fields = append(fields, hotel.FieldImage)
	}
	if m.FieldCleared(hotel.FieldHotelDetails) {
		fields = append(fields, hotel.FieldHotelDetails)
	}
	if m.FieldCleared(hotel.FieldURL) {
		fields = append(fields, hotel.FieldURL)
	}
	if m.FieldCleared(hotel.FieldStyleCode) {
		fields = append(fields, hotel.FieldStyleCode)
	}
	if m.FieldCleared(hotel.FieldCrawledAt) {
		fields = append(fields, hotel.FieldCrawledAt)
	}
	if m.FieldCleared(hotel.FieldEmbedding) {
		fields = append(fields, hotel.FieldEmbedding)
	}
	if m.FieldCleared(hotel.FieldSearchKeywords) {
		fields = append(fields, hotel.FieldSearchKeywords)
	}
	if m.FieldCleared(hotel.FieldPriceNumeric) {
		fields = append(fields, hotel.FieldPriceNumeric)
	}
	if m.FieldCleared(hotel.FieldRatingNumeric) {
		fields = append(fields, hotel.FieldRatingNumeric)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HotelMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HotelMutation) ClearField(name string) error {
	switch name {
	case hotel.FieldDescription:
		m.ClearDescription()
		return nil
	case hotel.FieldActualPrice:
		m.ClearActualPrice()
		return nil
	case hotel.FieldSellingPrice:
		m.ClearSellingPrice()
		return nil
	case hotel.FieldDiscount:
		m.ClearDiscount()
		return nil
	case hotel.FieldSeller:
		m.ClearSeller()
		return nil
	case hotel.FieldAverageRating:
		m.ClearAverageRating()
		return nil
	case hotel.FieldImage:
		m.ClearImage()
		return nil
	case hotel.FieldHotelDetails:
		m.ClearHotelDetails()
		return nil
	case hotel.FieldURL:
		m.ClearURL()
		return nil
	case hotel.FieldStyleCode:
		m.ClearStyleCode()
		return nil
	case hotel.FieldCrawledAt:
		m.ClearCrawledAt()
		return nil
	case hotel.FieldEmbedding:
		m.ClearEmbedding()
		return nil
	case hotel.FieldSearchKeywords:
		m.ClearSearchKeywords()
		return nil
	case hotel.FieldPriceNumeric:
		m.ClearPriceNumeric()
		return nil
	case hotel.FieldRatingNumeric:
		m.ClearRatingNumeric()
		return nil
	}
	return fmt.Errorf("unknown Hotel nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HotelMutation) ResetField(name string) error {
	switch name {
	case hotel.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case hotel.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case hotel.FieldOriginalID:
		m.ResetOriginalID()
		return nil
	case hotel.FieldTitle:
		m.ResetTitle()
		return nil
	case hotel.FieldBrand:
		m.ResetBrand()
		return nil
	case hotel.FieldDescription:
		m.ResetDescription()
		return nil
	case hotel.FieldActualPrice:
		m.ResetActualPrice()
		return nil
	case hotel.FieldSellingPrice:
		m.ResetSellingPrice()
		return nil
	case hotel.FieldDiscount:
		m.ResetDiscount()
		return nil
	case hotel.FieldCategory:
		m.ResetCategory()
		return nil
	case hotel.FieldSubCategory:
		m.ResetSubCategory()
		return nil
	case hotel.FieldOutOfStock:
		m.ResetOutOfStock()
		return nil
	case hotel.FieldSeller:
		m.ResetSeller()
		return nil
	case hotel.FieldAverageRating:
		m.ResetAverageRating()
		return nil
	case hotel.FieldImage:
		m.ResetImage()
		return nil
	case hotel.FieldHotelDetails:
		m.ResetHotelDetails()
		return nil
	case hotel.FieldURL:
		m.ResetURL()
		return nil
	case hotel.FieldPid:
		m.ResetPid()
		return nil
	case hotel.FieldStyleCode:
		m.ResetStyleCode()
		return nil
	case hotel.FieldCrawledAt:
		m.ResetCrawledAt()
		return nil
	case hotel.FieldEmbedding:
		m.ResetEmbedding()
		return nil
	case hotel.FieldSearchKeywords:
		m.ResetSearchKeywords()
		return nil
	case hotel.FieldFeatured:
		m.ResetFeatured()
		return nil
	case hotel.FieldViewCount:
		m.ResetViewCount()
		return nil
	case hotel.FieldClickCount:
		m.ResetClickCount()
		return nil
	case hotel.FieldPriceNumeric:
		m.ResetPriceNumeric()
		return nil
	case hotel.FieldRatingNumeric:
		m.ResetRatingNumeric()
		return nil
	}
	return fmt.Errorf("unknown Hotel field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HotelMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HotelMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HotelMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HotelMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HotelMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HotelMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HotelMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Hotel unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HotelMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Hotel edge %s", name)
}
