//go:build tools && tools && tools && tools && tools
// +build tools,tools,tools,tools,tools

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"yinni_travel_backend/ent/hotel"
	"yinni_travel_backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hotelMixin := schema.Hotel{}.Mixin()
	hotelMixinFields0 := hotelMixin[0].Fields()
	_ = hotelMixinFields0
	hotelFields := schema.Hotel{}.Fields()
	_ = hotelFields
	// hotelDescCreateTime is the schema descriptor for create_time field.
	hotelDescCreateTime := hotelMixinFields0[0].Descriptor()
	// hotel.DefaultCreateTime holds the default value on creation for the create_time field.
	hotel.DefaultCreateTime = hotelDescCreateTime.Default.(func() time.Time)
	// hotelDescUpdateTime is the schema descriptor for update_time field.
	hotelDescUpdateTime := hotelMixinFields0[1].Descriptor()
	// hotel.DefaultUpdateTime holds the default value on creation for the update_time field.
	hotel.DefaultUpdateTime = hotelDescUpdateTime.Default.(func() time.Time)
	// hotel.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	hotel.UpdateDefaultUpdateTime = hotelDescUpdateTime.UpdateDefault.(func() time.Time)
	// hotelDescTitle is the schema descriptor for title field.
	hotelDescTitle := hotelFields[1].Descriptor()
	// hotel.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	hotel.TitleValidator = hotelDescTitle.Validators[0].(func(string) error)
	// hotelDescBrand is the schema descriptor for brand field.
	hotelDescBrand := hotelFields[2].Descriptor()
	// hotel.BrandValidator is a validator for the "brand" field. It is called by the builders before save.
	hotel.BrandValidator = hotelDescBrand.Validators[0].(func(string) error)
	// hotelDescCategory is the schema descriptor for category field.
	hotelDescCategory := hotelFields[7].Descriptor()
	// hotel.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	hotel.CategoryValidator = hotelDescCategory.Validators[0].(func(string) error)
	// hotelDescSubCategory is the schema descriptor for sub_category field.
	hotelDescSubCategory := hotelFields[8].Descriptor()
	// hotel.SubCategoryValidator is a validator for the "sub_category" field. It is called by the builders before save.
	hotel.SubCategoryValidator = hotelDescSubCategory.Validators[0].(func(string) error)
	// hotelDescOutOfStock is the schema descriptor for out_of_stock field.
	hotelDescOutOfStock := hotelFields[9].Descriptor()
	// hotel.DefaultOutOfStock holds the default value on creation for the out_of_stock field.
	hotel.DefaultOutOfStock = hotelDescOutOfStock.Default.(bool)
	// hotelDescURL is the schema descriptor for url field.
	hotelDescURL := hotelFields[14].Descriptor()
	// hotel.URLValidator is a validator for the "url" field. It is called by the builders before save.
	hotel.URLValidator = hotelDescURL.Validators[0].(func(string) error)
	// hotelDescFeatured is the schema descriptor for featured field.
	hotelDescFeatured := hotelFields[20].Descriptor()
	// hotel.DefaultFeatured holds the default value on creation for the featured field.
	hotel.DefaultFeatured = hotelDescFeatured.Default.(bool)
	// hotelDescViewCount is the schema descriptor for view_count field.
	hotelDescViewCount := hotelFields[21].Descriptor()
	// hotel.DefaultViewCount holds the default value on creation for the view_count field.
	hotel.DefaultViewCount = hotelDescViewCount.Default.(int)
	// hotelDescClickCount is the schema descriptor for click_count field.
	hotelDescClickCount := hotelFields[22].Descriptor()
	// hotel.DefaultClickCount holds the default value on creation for the click_count field.
	hotel.DefaultClickCount = hotelDescClickCount.Default.(int)
	// hotelDescPriceNumeric is the schema descriptor for price_numeric field.
	hotelDescPriceNumeric := hotelFields[23].Descriptor()
	// hotel.PriceNumericValidator is a validator for the "price_numeric" field. It is called by the builders before save.
	hotel.PriceNumericValidator = hotelDescPriceNumeric.Validators[0].(func(int) error)
	// hotelDescRatingNumeric is the schema descriptor for rating_numeric field.
	hotelDescRatingNumeric := hotelFields[24].Descriptor()
	// hotel.RatingNumericValidator is a validator for the "rating_numeric" field. It is called by the builders before save.
	hotel.RatingNumericValidator = func() func(float64) error {
		validators := hotelDescRatingNumeric.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(rating_numeric float64) error {
			for _, fn := range fns {
				if err := fn(rating_numeric); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
