// Code generated by ent, DO NOT EDIT.

package hotel

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the hotel type in the database.
	Label = "hotel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldOriginalID holds the string denoting the original_id field in the database.
	FieldOriginalID = "original_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldBrand holds the string denoting the brand field in the database.
	FieldBrand = "brand"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldActualPrice holds the string denoting the actual_price field in the database.
	FieldActualPrice = "actual_price"
	// FieldSellingPrice holds the string denoting the selling_price field in the database.
	FieldSellingPrice = "selling_price"
	// FieldDiscount holds the string denoting the discount field in the database.
	FieldDiscount = "discount"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldSubCategory holds the string denoting the sub_category field in the database.
	FieldSubCategory = "sub_category"
	// FieldOutOfStock holds the string denoting the out_of_stock field in the database.
	FieldOutOfStock = "out_of_stock"
	// FieldSeller holds the string denoting the seller field in the database.
	FieldSeller = "seller"
	// FieldAverageRating holds the string denoting the average_rating field in the database.
	FieldAverageRating = "average_rating"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldHotelDetails holds the string denoting the hotel_details field in the database.
	FieldHotelDetails = "hotel_details"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldPid holds the string denoting the pid field in the database.
	FieldPid = "pid"
	// FieldStyleCode holds the string denoting the style_code field in the database.
	FieldStyleCode = "style_code"
	// FieldCrawledAt holds the string denoting the crawled_at field in the database.
	FieldCrawledAt = "crawled_at"
	// FieldEmbedding holds the string denoting the embedding field in the database.
	FieldEmbedding = "embedding"
	// FieldSearchKeywords holds the string denoting the search_keywords field in the database.
	FieldSearchKeywords = "search_keywords"
	// FieldFeatured holds the string denoting the featured field in the database.
	FieldFeatured = "featured"
	// FieldViewCount holds the string denoting the view_count field in the database.
	FieldViewCount = "view_count"
	// FieldClickCount holds the string denoting the click_count field in the database.
	FieldClickCount = "click_count"
	// FieldPriceNumeric holds the string denoting the price_numeric field in the database.
	FieldPriceNumeric = "price_numeric"
	// FieldRatingNumeric holds the string denoting the rating_numeric field in the database.
	FieldRatingNumeric = "rating_numeric"
	// Table holds the table name of the hotel in the database.
	Table = "hotels"
)

// Columns holds all SQL columns for hotel fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldOriginalID,
	FieldTitle,
	FieldBrand,
	FieldDescription,
	FieldActualPrice,
	FieldSellingPrice,
	FieldDiscount,
	FieldCategory,
	FieldSubCategory,
	FieldOutOfStock,
	FieldSeller,
	FieldAverageRating,
	FieldImage,
	FieldHotelDetails,
	FieldURL,
	FieldPid,
	FieldStyleCode,
	FieldCrawledAt,
	FieldEmbedding,
	FieldSearchKeywords,
	FieldFeatured,
	FieldViewCount,
	FieldClickCount,
	FieldPriceNumeric,
	FieldRatingNumeric,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// BrandValidator is a validator for the "brand" field. It is called by the builders before save.
	BrandValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// SubCategoryValidator is a validator for the "sub_category" field. It is called by the builders before save.
	SubCategoryValidator func(string) error
	// DefaultOutOfStock holds the default value on creation for the "out_of_stock" field.
	DefaultOutOfStock bool
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultFeatured holds the default value on creation for the "featured" field.
	DefaultFeatured bool
	// DefaultViewCount holds the default value on creation for the "view_count" field.
	DefaultViewCount int
	// DefaultClickCount holds the default value on creation for the "click_count" field.
	DefaultClickCount int
	// PriceNumericValidator is a validator for the "price_numeric" field. It is called by the builders before save.
	PriceNumericValidator func(int) error
	// RatingNumericValidator is a validator for the "rating_numeric" field. It is called by the builders before save.
	RatingNumericValidator func(float64) error
)

// OrderOption defines the ordering options for the Hotel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByOriginalID orders the results by the original_id field.
func ByOriginalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByBrand orders the results by the brand field.
func ByBrand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrand, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByActualPrice orders the results by the actual_price field.
func ByActualPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualPrice, opts...).ToFunc()
}

// BySellingPrice orders the results by the selling_price field.
func BySellingPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellingPrice, opts...).ToFunc()
}

// ByDiscount orders the results by the discount field.
func ByDiscount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscount, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// BySubCategory orders the results by the sub_category field.
func BySubCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubCategory, opts...).ToFunc()
}

// ByOutOfStock orders the results by the out_of_stock field.
func ByOutOfStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutOfStock, opts...).ToFunc()
}

// BySeller orders the results by the seller field.
func BySeller(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeller, opts...).ToFunc()
}

// ByAverageRating orders the results by the average_rating field.
func ByAverageRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAverageRating, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByPid orders the results by the pid field.
func ByPid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPid, opts...).ToFunc()
}

// ByStyleCode orders the results by the style_code field.
func ByStyleCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStyleCode, opts...).ToFunc()
}

// ByCrawledAt orders the results by the crawled_at field.
func ByCrawledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCrawledAt, opts...).ToFunc()
}

// ByFeatured orders the results by the featured field.
func ByFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatured, opts...).ToFunc()
}

// ByViewCount orders the results by the view_count field.
func ByViewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewCount, opts...).ToFunc()
}

// ByClickCount orders the results by the click_count field.
func ByClickCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClickCount, opts...).ToFunc()
}

// ByPriceNumeric orders the results by the price_numeric field.
func ByPriceNumeric(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceNumeric, opts...).ToFunc()
}

// ByRatingNumeric orders the results by the rating_numeric field.
func ByRatingNumeric(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatingNumeric, opts...).ToFunc()
}
