// Code generated by ent, DO NOT EDIT.

package hotel

import (
	"time"
	"yinni_travel_backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldUpdateTime, v))
}

// OriginalID applies equality check predicate on the "original_id" field. It's identical to OriginalIDEQ.
func OriginalID(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldOriginalID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldTitle, v))
}

// Brand applies equality check predicate on the "brand" field. It's identical to BrandEQ.
func Brand(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldBrand, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldDescription, v))
}

// ActualPrice applies equality check predicate on the "actual_price" field. It's identical to ActualPriceEQ.
func ActualPrice(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldActualPrice, v))
}

// SellingPrice applies equality check predicate on the "selling_price" field. It's identical to SellingPriceEQ.
func SellingPrice(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldSellingPrice, v))
}

// Discount applies equality check predicate on the "discount" field. It's identical to DiscountEQ.
func Discount(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldDiscount, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCategory, v))
}

// SubCategory applies equality check predicate on the "sub_category" field. It's identical to SubCategoryEQ.
func SubCategory(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldSubCategory, v))
}

// OutOfStock applies equality check predicate on the "out_of_stock" field. It's identical to OutOfStockEQ.
func OutOfStock(v bool) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldOutOfStock, v))
}

// Seller applies equality check predicate on the "seller" field. It's identical to SellerEQ.
func Seller(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldSeller, v))
}

// AverageRating applies equality check predicate on the "average_rating" field. It's identical to AverageRatingEQ.
func AverageRating(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldAverageRating, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldImage, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldURL, v))
}

// Pid applies equality check predicate on the "pid" field. It's identical to PidEQ.
func Pid(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldPid, v))
}

// StyleCode applies equality check predicate on the "style_code" field. It's identical to StyleCodeEQ.
func StyleCode(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldStyleCode, v))
}

// CrawledAt applies equality check predicate on the "crawled_at" field. It's identical to CrawledAtEQ.
func CrawledAt(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCrawledAt, v))
}

// Featured applies equality check predicate on the "featured" field. It's identical to FeaturedEQ.
func Featured(v bool) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldFeatured, v))
}

// ViewCount applies equality check predicate on the "view_count" field. It's identical to ViewCountEQ.
func ViewCount(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldViewCount, v))
}

// ClickCount applies equality check predicate on the "click_count" field. It's identical to ClickCountEQ.
func ClickCount(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldClickCount, v))
}

// PriceNumeric applies equality check predicate on the "price_numeric" field. It's identical to PriceNumericEQ.
func PriceNumeric(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldPriceNumeric, v))
}

// RatingNumeric applies equality check predicate on the "rating_numeric" field. It's identical to RatingNumericEQ.
func RatingNumeric(v float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldRatingNumeric, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldUpdateTime, v))
}

// OriginalIDEQ applies the EQ predicate on the "original_id" field.
func OriginalIDEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldOriginalID, v))
}

// OriginalIDNEQ applies the NEQ predicate on the "original_id" field.
func OriginalIDNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldOriginalID, v))
}

// OriginalIDIn applies the In predicate on the "original_id" field.
func OriginalIDIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldOriginalID, vs...))
}

// OriginalIDNotIn applies the NotIn predicate on the "original_id" field.
func OriginalIDNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldOriginalID, vs...))
}

// OriginalIDGT applies the GT predicate on the "original_id" field.
func OriginalIDGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldOriginalID, v))
}

// OriginalIDGTE applies the GTE predicate on the "original_id" field.
func OriginalIDGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldOriginalID, v))
}

// OriginalIDLT applies the LT predicate on the "original_id" field.
func OriginalIDLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldOriginalID, v))
}

// OriginalIDLTE applies the LTE predicate on the "original_id" field.
func OriginalIDLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldOriginalID, v))
}

// OriginalIDContains applies the Contains predicate on the "original_id" field.
func OriginalIDContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldOriginalID, v))
}

// OriginalIDHasPrefix applies the HasPrefix predicate on the "original_id" field.
func OriginalIDHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldOriginalID, v))
}

// OriginalIDHasSuffix applies the HasSuffix predicate on the "original_id" field.
func OriginalIDHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldOriginalID, v))
}

// OriginalIDEqualFold applies the EqualFold predicate on the "original_id" field.
func OriginalIDEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldOriginalID, v))
}

// OriginalIDContainsFold applies the ContainsFold predicate on the "original_id" field.
func OriginalIDContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldOriginalID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldTitle, v))
}

// BrandEQ applies the EQ predicate on the "brand" field.
func BrandEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldBrand, v))
}

// BrandNEQ applies the NEQ predicate on the "brand" field.
func BrandNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldBrand, v))
}

// BrandIn applies the In predicate on the "brand" field.
func BrandIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldBrand, vs...))
}

// BrandNotIn applies the NotIn predicate on the "brand" field.
func BrandNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldBrand, vs...))
}

// BrandGT applies the GT predicate on the "brand" field.
func BrandGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldBrand, v))
}

// BrandGTE applies the GTE predicate on the "brand" field.
func BrandGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldBrand, v))
}

// BrandLT applies the LT predicate on the "brand" field.
func BrandLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldBrand, v))
}

// BrandLTE applies the LTE predicate on the "brand" field.
func BrandLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldBrand, v))
}

// BrandContains applies the Contains predicate on the "brand" field.
func BrandContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldBrand, v))
}

// BrandHasPrefix applies the HasPrefix predicate on the "brand" field.
func BrandHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldBrand, v))
}

// BrandHasSuffix applies the HasSuffix predicate on the "brand" field.
func BrandHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldBrand, v))
}

// BrandEqualFold applies the EqualFold predicate on the "brand" field.
func BrandEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldBrand, v))
}

// BrandContainsFold applies the ContainsFold predicate on the "brand" field.
func BrandContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldBrand, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldDescription, v))
}

// ActualPriceEQ applies the EQ predicate on the "actual_price" field.
func ActualPriceEQ(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldActualPrice, v))
}

// ActualPriceNEQ applies the NEQ predicate on the "actual_price" field.
func ActualPriceNEQ(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldActualPrice, v))
}

// ActualPriceIn applies the In predicate on the "actual_price" field.
func ActualPriceIn(vs ...float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldActualPrice, vs...))
}

// ActualPriceNotIn applies the NotIn predicate on the "actual_price" field.
func ActualPriceNotIn(vs ...float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldActualPrice, vs...))
}

// ActualPriceGT applies the GT predicate on the "actual_price" field.
func ActualPriceGT(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldActualPrice, v))
}

// ActualPriceGTE applies the GTE predicate on the "actual_price" field.
func ActualPriceGTE(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldActualPrice, v))
}

// ActualPriceLT applies the LT predicate on the "actual_price" field.
func ActualPriceLT(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldActualPrice, v))
}

// ActualPriceLTE applies the LTE predicate on the "actual_price" field.
func ActualPriceLTE(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldActualPrice, v))
}

// ActualPriceIsNil applies the IsNil predicate on the "actual_price" field.
func ActualPriceIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldActualPrice))
}

// ActualPriceNotNil applies the NotNil predicate on the "actual_price" field.
func ActualPriceNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldActualPrice))
}

// SellingPriceEQ applies the EQ predicate on the "selling_price" field.
func SellingPriceEQ(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldSellingPrice, v))
}

// SellingPriceNEQ applies the NEQ predicate on the "selling_price" field.
func SellingPriceNEQ(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldSellingPrice, v))
}

// SellingPriceIn applies the In predicate on the "selling_price" field.
func SellingPriceIn(vs ...float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldSellingPrice, vs...))
}

// SellingPriceNotIn applies the NotIn predicate on the "selling_price" field.
func SellingPriceNotIn(vs ...float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldSellingPrice, vs...))
}

// SellingPriceGT applies the GT predicate on the "selling_price" field.
func SellingPriceGT(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldSellingPrice, v))
}

// SellingPriceGTE applies the GTE predicate on the "selling_price" field.
func SellingPriceGTE(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldSellingPrice, v))
}

// SellingPriceLT applies the LT predicate on the "selling_price" field.
func SellingPriceLT(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldSellingPrice, v))
}

// SellingPriceLTE applies the LTE predicate on the "selling_price" field.
func SellingPriceLTE(v float32) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldSellingPrice, v))
}

// SellingPriceIsNil applies the IsNil predicate on the "selling_price" field.
func SellingPriceIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldSellingPrice))
}

// SellingPriceNotNil applies the NotNil predicate on the "selling_price" field.
func SellingPriceNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldSellingPrice))
}

// DiscountEQ applies the EQ predicate on the "discount" field.
func DiscountEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldDiscount, v))
}

// DiscountNEQ applies the NEQ predicate on the "discount" field.
func DiscountNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldDiscount, v))
}

// DiscountIn applies the In predicate on the "discount" field.
func DiscountIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldDiscount, vs...))
}

// DiscountNotIn applies the NotIn predicate on the "discount" field.
func DiscountNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldDiscount, vs...))
}

// DiscountGT applies the GT predicate on the "discount" field.
func DiscountGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldDiscount, v))
}

// DiscountGTE applies the GTE predicate on the "discount" field.
func DiscountGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldDiscount, v))
}

// DiscountLT applies the LT predicate on the "discount" field.
func DiscountLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldDiscount, v))
}

// DiscountLTE applies the LTE predicate on the "discount" field.
func DiscountLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldDiscount, v))
}

// DiscountContains applies the Contains predicate on the "discount" field.
func DiscountContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldDiscount, v))
}

// DiscountHasPrefix applies the HasPrefix predicate on the "discount" field.
func DiscountHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldDiscount, v))
}

// DiscountHasSuffix applies the HasSuffix predicate on the "discount" field.
func DiscountHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldDiscount, v))
}

// DiscountIsNil applies the IsNil predicate on the "discount" field.
func DiscountIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldDiscount))
}

// DiscountNotNil applies the NotNil predicate on the "discount" field.
func DiscountNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldDiscount))
}

// DiscountEqualFold applies the EqualFold predicate on the "discount" field.
func DiscountEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldDiscount, v))
}

// DiscountContainsFold applies the ContainsFold predicate on the "discount" field.
func DiscountContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldDiscount, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldCategory, v))
}

// SubCategoryEQ applies the EQ predicate on the "sub_category" field.
func SubCategoryEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldSubCategory, v))
}

// SubCategoryNEQ applies the NEQ predicate on the "sub_category" field.
func SubCategoryNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldSubCategory, v))
}

// SubCategoryIn applies the In predicate on the "sub_category" field.
func SubCategoryIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldSubCategory, vs...))
}

// SubCategoryNotIn applies the NotIn predicate on the "sub_category" field.
func SubCategoryNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldSubCategory, vs...))
}

// SubCategoryGT applies the GT predicate on the "sub_category" field.
func SubCategoryGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldSubCategory, v))
}

// SubCategoryGTE applies the GTE predicate on the "sub_category" field.
func SubCategoryGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldSubCategory, v))
}

// SubCategoryLT applies the LT predicate on the "sub_category" field.
func SubCategoryLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldSubCategory, v))
}

// SubCategoryLTE applies the LTE predicate on the "sub_category" field.
func SubCategoryLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldSubCategory, v))
}

// SubCategoryContains applies the Contains predicate on the "sub_category" field.
func SubCategoryContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldSubCategory, v))
}

// SubCategoryHasPrefix applies the HasPrefix predicate on the "sub_category" field.
func SubCategoryHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldSubCategory, v))
}

// SubCategoryHasSuffix applies the HasSuffix predicate on the "sub_category" field.
func SubCategoryHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldSubCategory, v))
}

// SubCategoryEqualFold applies the EqualFold predicate on the "sub_category" field.
func SubCategoryEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldSubCategory, v))
}

// SubCategoryContainsFold applies the ContainsFold predicate on the "sub_category" field.
func SubCategoryContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldSubCategory, v))
}

// OutOfStockEQ applies the EQ predicate on the "out_of_stock" field.
func OutOfStockEQ(v bool) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldOutOfStock, v))
}

// OutOfStockNEQ applies the NEQ predicate on the "out_of_stock" field.
func OutOfStockNEQ(v bool) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldOutOfStock, v))
}

// SellerEQ applies the EQ predicate on the "seller" field.
func SellerEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldSeller, v))
}

// SellerNEQ applies the NEQ predicate on the "seller" field.
func SellerNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldSeller, v))
}

// SellerIn applies the In predicate on the "seller" field.
func SellerIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldSeller, vs...))
}

// SellerNotIn applies the NotIn predicate on the "seller" field.
func SellerNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldSeller, vs...))
}

// SellerGT applies the GT predicate on the "seller" field.
func SellerGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldSeller, v))
}

// SellerGTE applies the GTE predicate on the "seller" field.
func SellerGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldSeller, v))
}

// SellerLT applies the LT predicate on the "seller" field.
func SellerLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldSeller, v))
}

// SellerLTE applies the LTE predicate on the "seller" field.
func SellerLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldSeller, v))
}

// SellerContains applies the Contains predicate on the "seller" field.
func SellerContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldSeller, v))
}

// SellerHasPrefix applies the HasPrefix predicate on the "seller" field.
func SellerHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldSeller, v))
}

// SellerHasSuffix applies the HasSuffix predicate on the "seller" field.
func SellerHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldSeller, v))
}

// SellerIsNil applies the IsNil predicate on the "seller" field.
func SellerIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldSeller))
}

// SellerNotNil applies the NotNil predicate on the "seller" field.
func SellerNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldSeller))
}

// SellerEqualFold applies the EqualFold predicate on the "seller" field.
func SellerEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldSeller, v))
}

// SellerContainsFold applies the ContainsFold predicate on the "seller" field.
func SellerContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldSeller, v))
}

// AverageRatingEQ applies the EQ predicate on the "average_rating" field.
func AverageRatingEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldAverageRating, v))
}

// AverageRatingNEQ applies the NEQ predicate on the "average_rating" field.
func AverageRatingNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldAverageRating, v))
}

// AverageRatingIn applies the In predicate on the "average_rating" field.
func AverageRatingIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldAverageRating, vs...))
}

// AverageRatingNotIn applies the NotIn predicate on the "average_rating" field.
func AverageRatingNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldAverageRating, vs...))
}

// AverageRatingGT applies the GT predicate on the "average_rating" field.
func AverageRatingGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldAverageRating, v))
}

// AverageRatingGTE applies the GTE predicate on the "average_rating" field.
func AverageRatingGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldAverageRating, v))
}

// AverageRatingLT applies the LT predicate on the "average_rating" field.
func AverageRatingLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldAverageRating, v))
}

// AverageRatingLTE applies the LTE predicate on the "average_rating" field.
func AverageRatingLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldAverageRating, v))
}

// AverageRatingContains applies the Contains predicate on the "average_rating" field.
func AverageRatingContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldAverageRating, v))
}

// AverageRatingHasPrefix applies the HasPrefix predicate on the "average_rating" field.
func AverageRatingHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldAverageRating, v))
}

// AverageRatingHasSuffix applies the HasSuffix predicate on the "average_rating" field.
func AverageRatingHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldAverageRating, v))
}

// AverageRatingIsNil applies the IsNil predicate on the "average_rating" field.
func AverageRatingIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldAverageRating))
}

// AverageRatingNotNil applies the NotNil predicate on the "average_rating" field.
func AverageRatingNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldAverageRating))
}

// AverageRatingEqualFold applies the EqualFold predicate on the "average_rating" field.
func AverageRatingEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldAverageRating, v))
}

// AverageRatingContainsFold applies the ContainsFold predicate on the "average_rating" field.
func AverageRatingContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldAverageRating, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldImage, v))
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldImage))
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldImage))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldImage, v))
}

// HotelDetailsIsNil applies the IsNil predicate on the "hotel_details" field.
func HotelDetailsIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldHotelDetails))
}

// HotelDetailsNotNil applies the NotNil predicate on the "hotel_details" field.
func HotelDetailsNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldHotelDetails))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldURL, v))
}

// PidEQ applies the EQ predicate on the "pid" field.
func PidEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldPid, v))
}

// PidNEQ applies the NEQ predicate on the "pid" field.
func PidNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldPid, v))
}

// PidIn applies the In predicate on the "pid" field.
func PidIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldPid, vs...))
}

// PidNotIn applies the NotIn predicate on the "pid" field.
func PidNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldPid, vs...))
}

// PidGT applies the GT predicate on the "pid" field.
func PidGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldPid, v))
}

// PidGTE applies the GTE predicate on the "pid" field.
func PidGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldPid, v))
}

// PidLT applies the LT predicate on the "pid" field.
func PidLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldPid, v))
}

// PidLTE applies the LTE predicate on the "pid" field.
func PidLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldPid, v))
}

// PidContains applies the Contains predicate on the "pid" field.
func PidContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldPid, v))
}

// PidHasPrefix applies the HasPrefix predicate on the "pid" field.
func PidHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldPid, v))
}

// PidHasSuffix applies the HasSuffix predicate on the "pid" field.
func PidHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldPid, v))
}

// PidEqualFold applies the EqualFold predicate on the "pid" field.
func PidEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldPid, v))
}

// PidContainsFold applies the ContainsFold predicate on the "pid" field.
func PidContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldPid, v))
}

// StyleCodeEQ applies the EQ predicate on the "style_code" field.
func StyleCodeEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldStyleCode, v))
}

// StyleCodeNEQ applies the NEQ predicate on the "style_code" field.
func StyleCodeNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldStyleCode, v))
}

// StyleCodeIn applies the In predicate on the "style_code" field.
func StyleCodeIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldStyleCode, vs...))
}

// StyleCodeNotIn applies the NotIn predicate on the "style_code" field.
func StyleCodeNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldStyleCode, vs...))
}

// StyleCodeGT applies the GT predicate on the "style_code" field.
func StyleCodeGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldStyleCode, v))
}

// StyleCodeGTE applies the GTE predicate on the "style_code" field.
func StyleCodeGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldStyleCode, v))
}

// StyleCodeLT applies the LT predicate on the "style_code" field.
func StyleCodeLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldStyleCode, v))
}

// StyleCodeLTE applies the LTE predicate on the "style_code" field.
func StyleCodeLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldStyleCode, v))
}

// StyleCodeContains applies the Contains predicate on the "style_code" field.
func StyleCodeContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldStyleCode, v))
}

// StyleCodeHasPrefix applies the HasPrefix predicate on the "style_code" field.
func StyleCodeHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldStyleCode, v))
}

// StyleCodeHasSuffix applies the HasSuffix predicate on the "style_code" field.
func StyleCodeHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldStyleCode, v))
}

// StyleCodeIsNil applies the IsNil predicate on the "style_code" field.
func StyleCodeIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldStyleCode))
}

// StyleCodeNotNil applies the NotNil predicate on the "style_code" field.
func StyleCodeNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldStyleCode))
}

// StyleCodeEqualFold applies the EqualFold predicate on the "style_code" field.
func StyleCodeEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldStyleCode, v))
}

// StyleCodeContainsFold applies the ContainsFold predicate on the "style_code" field.
func StyleCodeContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldStyleCode, v))
}

// CrawledAtEQ applies the EQ predicate on the "crawled_at" field.
func CrawledAtEQ(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCrawledAt, v))
}

// CrawledAtNEQ applies the NEQ predicate on the "crawled_at" field.
func CrawledAtNEQ(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldCrawledAt, v))
}

// CrawledAtIn applies the In predicate on the "crawled_at" field.
func CrawledAtIn(vs ...time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldCrawledAt, vs...))
}

// CrawledAtNotIn applies the NotIn predicate on the "crawled_at" field.
func CrawledAtNotIn(vs ...time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldCrawledAt, vs...))
}

// CrawledAtGT applies the GT predicate on the "crawled_at" field.
func CrawledAtGT(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldCrawledAt, v))
}

// CrawledAtGTE applies the GTE predicate on the "crawled_at" field.
func CrawledAtGTE(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldCrawledAt, v))
}

// CrawledAtLT applies the LT predicate on the "crawled_at" field.
func CrawledAtLT(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldCrawledAt, v))
}

// CrawledAtLTE applies the LTE predicate on the "crawled_at" field.
func CrawledAtLTE(v time.Time) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldCrawledAt, v))
}

// CrawledAtIsNil applies the IsNil predicate on the "crawled_at" field.
func CrawledAtIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldCrawledAt))
}

// CrawledAtNotNil applies the NotNil predicate on the "crawled_at" field.
func CrawledAtNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldCrawledAt))
}

// EmbeddingIsNil applies the IsNil predicate on the "embedding" field.
func EmbeddingIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldEmbedding))
}

// EmbeddingNotNil applies the NotNil predicate on the "embedding" field.
func EmbeddingNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldEmbedding))
}

// SearchKeywordsIsNil applies the IsNil predicate on the "search_keywords" field.
func SearchKeywordsIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldSearchKeywords))
}

// SearchKeywordsNotNil applies the NotNil predicate on the "search_keywords" field.
func SearchKeywordsNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldSearchKeywords))
}

// FeaturedEQ applies the EQ predicate on the "featured" field.
func FeaturedEQ(v bool) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldFeatured, v))
}

// FeaturedNEQ applies the NEQ predicate on the "featured" field.
func FeaturedNEQ(v bool) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldFeatured, v))
}

// ViewCountEQ applies the EQ predicate on the "view_count" field.
func ViewCountEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldViewCount, v))
}

// ViewCountNEQ applies the NEQ predicate on the "view_count" field.
func ViewCountNEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldViewCount, v))
}

// ViewCountIn applies the In predicate on the "view_count" field.
func ViewCountIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldViewCount, vs...))
}

// ViewCountNotIn applies the NotIn predicate on the "view_count" field.
func ViewCountNotIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldViewCount, vs...))
}

// ViewCountGT applies the GT predicate on the "view_count" field.
func ViewCountGT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldViewCount, v))
}

// ViewCountGTE applies the GTE predicate on the "view_count" field.
func ViewCountGTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldViewCount, v))
}

// ViewCountLT applies the LT predicate on the "view_count" field.
func ViewCountLT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldViewCount, v))
}

// ViewCountLTE applies the LTE predicate on the "view_count" field.
func ViewCountLTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldViewCount, v))
}

// ClickCountEQ applies the EQ predicate on the "click_count" field.
func ClickCountEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldClickCount, v))
}

// ClickCountNEQ applies the NEQ predicate on the "click_count" field.
func ClickCountNEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldClickCount, v))
}

// ClickCountIn applies the In predicate on the "click_count" field.
func ClickCountIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldClickCount, vs...))
}

// ClickCountNotIn applies the NotIn predicate on the "click_count" field.
func ClickCountNotIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldClickCount, vs...))
}

// ClickCountGT applies the GT predicate on the "click_count" field.
func ClickCountGT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldClickCount, v))
}

// ClickCountGTE applies the GTE predicate on the "click_count" field.
func ClickCountGTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldClickCount, v))
}

// ClickCountLT applies the LT predicate on the "click_count" field.
func ClickCountLT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldClickCount, v))
}

// ClickCountLTE applies the LTE predicate on the "click_count" field.
func ClickCountLTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldClickCount, v))
}

// PriceNumericEQ applies the EQ predicate on the "price_numeric" field.
func PriceNumericEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldPriceNumeric, v))
}

// PriceNumericNEQ applies the NEQ predicate on the "price_numeric" field.
func PriceNumericNEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldPriceNumeric, v))
}

// PriceNumericIn applies the In predicate on the "price_numeric" field.
func PriceNumericIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldPriceNumeric, vs...))
}

// PriceNumericNotIn applies the NotIn predicate on the "price_numeric" field.
func PriceNumericNotIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldPriceNumeric, vs...))
}

// PriceNumericGT applies the GT predicate on the "price_numeric" field.
func PriceNumericGT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldPriceNumeric, v))
}

// PriceNumericGTE applies the GTE predicate on the "price_numeric" field.
func PriceNumericGTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldPriceNumeric, v))
}

// PriceNumericLT applies the LT predicate on the "price_numeric" field.
func PriceNumericLT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldPriceNumeric, v))
}

// PriceNumericLTE applies the LTE predicate on the "price_numeric" field.
func PriceNumericLTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldPriceNumeric, v))
}

// PriceNumericIsNil applies the IsNil predicate on the "price_numeric" field.
func PriceNumericIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldPriceNumeric))
}

// PriceNumericNotNil applies the NotNil predicate on the "price_numeric" field.
func PriceNumericNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldPriceNumeric))
}

// RatingNumericEQ applies the EQ predicate on the "rating_numeric" field.
func RatingNumericEQ(v float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldRatingNumeric, v))
}

// RatingNumericNEQ applies the NEQ predicate on the "rating_numeric" field.
func RatingNumericNEQ(v float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldRatingNumeric, v))
}

// RatingNumericIn applies the In predicate on the "rating_numeric" field.
func RatingNumericIn(vs ...float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldRatingNumeric, vs...))
}

// RatingNumericNotIn applies the NotIn predicate on the "rating_numeric" field.
func RatingNumericNotIn(vs ...float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldRatingNumeric, vs...))
}

// RatingNumericGT applies the GT predicate on the "rating_numeric" field.
func RatingNumericGT(v float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldRatingNumeric, v))
}

// RatingNumericGTE applies the GTE predicate on the "rating_numeric" field.
func RatingNumericGTE(v float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldRatingNumeric, v))
}

// RatingNumericLT applies the LT predicate on the "rating_numeric" field.
func RatingNumericLT(v float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldRatingNumeric, v))
}

// RatingNumericLTE applies the LTE predicate on the "rating_numeric" field.
func RatingNumericLTE(v float64) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldRatingNumeric, v))
}

// RatingNumericIsNil applies the IsNil predicate on the "rating_numeric" field.
func RatingNumericIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldRatingNumeric))
}

// RatingNumericNotNil applies the NotNil predicate on the "rating_numeric" field.
func RatingNumericNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldRatingNumeric))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Hotel) predicate.Hotel {
	return predicate.Hotel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Hotel) predicate.Hotel {
	return predicate.Hotel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Hotel) predicate.Hotel {
	return predicate.Hotel(sql.NotPredicates(p))
}
