// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"yinni_travel_backend/app/hotels/internal/biz"
	"yinni_travel_backend/app/hotels/internal/data"
	"yinni_travel_backend/app/hotels/internal/server"
	"yinni_travel_backend/app/hotels/internal/service"
	"yinni_travel_backend/internal/conf"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, auth *conf.Auth, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	hotelsRepo := data.NewHotelsRepo(dataData, logger)
	hotelsUsecase := biz.NewHotelsUsecase(hotelsRepo)
	hotelsService := service.NewHotelsService(hotelsUsecase)
	grpcServer := server.NewGRPCServer(confServer, hotelsService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, hotelsService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
