// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: hotels/v1/hotels.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHotelGetHotel = "/api.hotel.v1.Hotel/GetHotel"
const OperationHotelListHotels = "/api.hotel.v1.Hotel/ListHotels"
const OperationHotelSearchHotels = "/api.hotel.v1.Hotel/SearchHotels"
const OperationHotelSeedHotelsDatabase = "/api.hotel.v1.Hotel/SeedHotelsDatabase"

type HotelHTTPServer interface {
	// GetHotel Get hotel by ID
	GetHotel(context.Context, *GetHotelRequest) (*HotelInfo, error)
	// ListHotels List hotels
	ListHotels(context.Context, *ListHotelsRequest) (*ListHotelsReply, error)
	// SearchHotels Search hotels
	SearchHotels(context.Context, *SearchHotelsRequest) (*ListHotelsReply, error)
	// SeedHotelsDatabase seed database
	SeedHotelsDatabase(context.Context, *SeedHotelsDatabaseRequest) (*SeedHotelsDatabaseReply, error)
}

func RegisterHotelHTTPServer(s *http.Server, srv HotelHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/hotels/id/{id}", _Hotel_GetHotel0_HTTP_Handler(srv))
	r.GET("/v1/hotels", _Hotel_ListHotels0_HTTP_Handler(srv))
	r.GET("/v1/hotels/search", _Hotel_SearchHotels0_HTTP_Handler(srv))
	r.POST("/v1/hotels/seed", _Hotel_SeedHotelsDatabase0_HTTP_Handler(srv))
}

func _Hotel_GetHotel0_HTTP_Handler(srv HotelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHotelRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHotelGetHotel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHotel(ctx, req.(*GetHotelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HotelInfo)
		return ctx.Result(200, reply)
	}
}

func _Hotel_ListHotels0_HTTP_Handler(srv HotelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListHotelsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHotelListHotels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHotels(ctx, req.(*ListHotelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListHotelsReply)
		return ctx.Result(200, reply)
	}
}

func _Hotel_SearchHotels0_HTTP_Handler(srv HotelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchHotelsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHotelSearchHotels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchHotels(ctx, req.(*SearchHotelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListHotelsReply)
		return ctx.Result(200, reply)
	}
}

func _Hotel_SeedHotelsDatabase0_HTTP_Handler(srv HotelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SeedHotelsDatabaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHotelSeedHotelsDatabase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SeedHotelsDatabase(ctx, req.(*SeedHotelsDatabaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SeedHotelsDatabaseReply)
		return ctx.Result(200, reply)
	}
}

type HotelHTTPClient interface {
	// GetHotel Get hotel by ID
	GetHotel(ctx context.Context, req *GetHotelRequest, opts ...http.CallOption) (rsp *HotelInfo, err error)
	// ListHotels List hotels
	ListHotels(ctx context.Context, req *ListHotelsRequest, opts ...http.CallOption) (rsp *ListHotelsReply, err error)
	// SearchHotels Search hotels
	SearchHotels(ctx context.Context, req *SearchHotelsRequest, opts ...http.CallOption) (rsp *ListHotelsReply, err error)
	// SeedHotelsDatabase seed database
	SeedHotelsDatabase(ctx context.Context, req *SeedHotelsDatabaseRequest, opts ...http.CallOption) (rsp *SeedHotelsDatabaseReply, err error)
}

type HotelHTTPClientImpl struct {
	cc *http.Client
}

func NewHotelHTTPClient(client *http.Client) HotelHTTPClient {
	return &HotelHTTPClientImpl{client}
}

// GetHotel Get hotel by ID
func (c *HotelHTTPClientImpl) GetHotel(ctx context.Context, in *GetHotelRequest, opts ...http.CallOption) (*HotelInfo, error) {
	var out HotelInfo
	pattern := "/v1/hotels/id/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHotelGetHotel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListHotels List hotels
func (c *HotelHTTPClientImpl) ListHotels(ctx context.Context, in *ListHotelsRequest, opts ...http.CallOption) (*ListHotelsReply, error) {
	var out ListHotelsReply
	pattern := "/v1/hotels"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHotelListHotels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchHotels Search hotels
func (c *HotelHTTPClientImpl) SearchHotels(ctx context.Context, in *SearchHotelsRequest, opts ...http.CallOption) (*ListHotelsReply, error) {
	var out ListHotelsReply
	pattern := "/v1/hotels/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHotelSearchHotels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SeedHotelsDatabase seed database
func (c *HotelHTTPClientImpl) SeedHotelsDatabase(ctx context.Context, in *SeedHotelsDatabaseRequest, opts ...http.CallOption) (*SeedHotelsDatabaseReply, error) {
	var out SeedHotelsDatabaseReply
	pattern := "/v1/hotels/seed"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHotelSeedHotelsDatabase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
