// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/hotels/v1/hotels.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hotel_GetHotel_FullMethodName     = "/api.hotel.v1.Hotel/GetHotel"
	Hotel_ListHotels_FullMethodName   = "/api.hotel.v1.Hotel/ListHotels"
	Hotel_SearchHotels_FullMethodName = "/api.hotel.v1.Hotel/SearchHotels"
)

// HotelClient is the client API for Hotel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HotelClient interface {
	// Get hotel by ID
	GetHotel(ctx context.Context, in *GetHotelRequest, opts ...grpc.CallOption) (*HotelInfo, error)
	// List hotels
	ListHotels(ctx context.Context, in *ListHotelsRequest, opts ...grpc.CallOption) (*ListHotelsReply, error)
	// Search hotels
	SearchHotels(ctx context.Context, in *SearchHotelsRequest, opts ...grpc.CallOption) (*ListHotelsReply, error)
}

type hotelClient struct {
	cc grpc.ClientConnInterface
}

func NewHotelClient(cc grpc.ClientConnInterface) HotelClient {
	return &hotelClient{cc}
}

func (c *hotelClient) GetHotel(ctx context.Context, in *GetHotelRequest, opts ...grpc.CallOption) (*HotelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotelInfo)
	err := c.cc.Invoke(ctx, Hotel_GetHotel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelClient) ListHotels(ctx context.Context, in *ListHotelsRequest, opts ...grpc.CallOption) (*ListHotelsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHotelsReply)
	err := c.cc.Invoke(ctx, Hotel_ListHotels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelClient) SearchHotels(ctx context.Context, in *SearchHotelsRequest, opts ...grpc.CallOption) (*ListHotelsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHotelsReply)
	err := c.cc.Invoke(ctx, Hotel_SearchHotels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotelServer is the server API for Hotel service.
// All implementations must embed UnimplementedHotelServer
// for forward compatibility.
type HotelServer interface {
	// Get hotel by ID
	GetHotel(context.Context, *GetHotelRequest) (*HotelInfo, error)
	// List hotels
	ListHotels(context.Context, *ListHotelsRequest) (*ListHotelsReply, error)
	// Search hotels
	SearchHotels(context.Context, *SearchHotelsRequest) (*ListHotelsReply, error)
	mustEmbedUnimplementedHotelServer()
}

// UnimplementedHotelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHotelServer struct{}

func (UnimplementedHotelServer) GetHotel(context.Context, *GetHotelRequest) (*HotelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotel not implemented")
}
func (UnimplementedHotelServer) ListHotels(context.Context, *ListHotelsRequest) (*ListHotelsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHotels not implemented")
}
func (UnimplementedHotelServer) SearchHotels(context.Context, *SearchHotelsRequest) (*ListHotelsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchHotels not implemented")
}
func (UnimplementedHotelServer) mustEmbedUnimplementedHotelServer() {}
func (UnimplementedHotelServer) testEmbeddedByValue()               {}

// UnsafeHotelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotelServer will
// result in compilation errors.
type UnsafeHotelServer interface {
	mustEmbedUnimplementedHotelServer()
}

func RegisterHotelServer(s grpc.ServiceRegistrar, srv HotelServer) {
	// If the following call panics, it indicates UnimplementedHotelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hotel_ServiceDesc, srv)
}

func _Hotel_GetHotel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServer).GetHotel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hotel_GetHotel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServer).GetHotel(ctx, req.(*GetHotelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hotel_ListHotels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHotelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServer).ListHotels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hotel_ListHotels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServer).ListHotels(ctx, req.(*ListHotelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hotel_SearchHotels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHotelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServer).SearchHotels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hotel_SearchHotels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServer).SearchHotels(ctx, req.(*SearchHotelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hotel_ServiceDesc is the grpc.ServiceDesc for Hotel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hotel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.hotel.v1.Hotel",
	HandlerType: (*HotelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotel",
			Handler:    _Hotel_GetHotel_Handler,
		},
		{
			MethodName: "ListHotels",
			Handler:    _Hotel_ListHotels_Handler,
		},
		{
			MethodName: "SearchHotels",
			Handler:    _Hotel_SearchHotels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/hotels/v1/hotels.proto",
}
