// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/hotels/v1/hotels.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelRequest) Reset() {
	*x = GetHotelRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelRequest) ProtoMessage() {}

func (x *GetHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelRequest.ProtoReflect.Descriptor instead.
func (*GetHotelRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Brand         string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	SubCategory   string                 `protobuf:"bytes,5,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	MinPrice      int32                  `protobuf:"varint,6,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int32                  `protobuf:"varint,7,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	MinRating     float32                `protobuf:"fixed32,8,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`
	InStock       bool                   `protobuf:"varint,9,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	FeaturedOnly  bool                   `protobuf:"varint,10,opt,name=featured_only,json=featuredOnly,proto3" json:"featured_only,omitempty"`
	Seller        string                 `protobuf:"bytes,11,opt,name=seller,proto3" json:"seller,omitempty"`
	SortBy        string                 `protobuf:"bytes,12,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // "price", "rating", "newest", "popular"
	SortOrder     string                 `protobuf:"bytes,13,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc", "desc"
	SearchQuery   string                 `protobuf:"bytes,14,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHotelsRequest) Reset() {
	*x = ListHotelsRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotelsRequest) ProtoMessage() {}

func (x *ListHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotelsRequest.ProtoReflect.Descriptor instead.
func (*ListHotelsRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *ListHotelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListHotelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListHotelsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListHotelsRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ListHotelsRequest) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *ListHotelsRequest) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ListHotelsRequest) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ListHotelsRequest) GetMinRating() float32 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *ListHotelsRequest) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *ListHotelsRequest) GetFeaturedOnly() bool {
	if x != nil {
		return x.FeaturedOnly
	}
	return false
}

func (x *ListHotelsRequest) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *ListHotelsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListHotelsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListHotelsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type SearchHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	PriceRange    *PriceRange            `protobuf:"bytes,4,opt,name=price_range,json=priceRange,proto3" json:"price_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHotelsRequest) Reset() {
	*x = SearchHotelsRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelsRequest) ProtoMessage() {}

func (x *SearchHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelsRequest.ProtoReflect.Descriptor instead.
func (*SearchHotelsRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *SearchHotelsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchHotelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchHotelsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchHotelsRequest) GetPriceRange() *PriceRange {
	if x != nil {
		return x.PriceRange
	}
	return nil
}

type GetFeaturedHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturedHotelsRequest) Reset() {
	*x = GetFeaturedHotelsRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturedHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturedHotelsRequest) ProtoMessage() {}

func (x *GetFeaturedHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturedHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetFeaturedHotelsRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeaturedHotelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFeaturedHotelsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetSimilarHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarHotelsRequest) Reset() {
	*x = GetSimilarHotelsRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarHotelsRequest) ProtoMessage() {}

func (x *GetSimilarHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarHotelsRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{4}
}

func (x *GetSimilarHotelsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetSimilarHotelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GenerateEmbeddingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegenerateAll bool                   `protobuf:"varint,1,opt,name=regenerate_all,json=regenerateAll,proto3" json:"regenerate_all,omitempty"` // Whether to regenerate all embeddings
	BatchSize     int32                  `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`             // Batch size for processing
	HotelIds      []int64                `protobuf:"varint,3,rep,packed,name=hotel_ids,json=hotelIds,proto3" json:"hotel_ids,omitempty"`         // Specific hotels to process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateEmbeddingsRequest) Reset() {
	*x = GenerateEmbeddingsRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEmbeddingsRequest) ProtoMessage() {}

func (x *GenerateEmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*GenerateEmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateEmbeddingsRequest) GetRegenerateAll() bool {
	if x != nil {
		return x.RegenerateAll
	}
	return false
}

func (x *GenerateEmbeddingsRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *GenerateEmbeddingsRequest) GetHotelIds() []int64 {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

type GetEmbeddingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbeddingStatusRequest) Reset() {
	*x = GetEmbeddingStatusRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbeddingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbeddingStatusRequest) ProtoMessage() {}

func (x *GetEmbeddingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbeddingStatusRequest.ProtoReflect.Descriptor instead.
func (*GetEmbeddingStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{6}
}

func (x *GetEmbeddingStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StartHotelSeedJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClearExisting bool                   `protobuf:"varint,1,opt,name=clear_existing,json=clearExisting,proto3" json:"clear_existing,omitempty"`
	MaxHotels     int32                  `protobuf:"varint,2,opt,name=max_hotels,json=maxHotels,proto3" json:"max_hotels,omitempty"` // 0 means seed all hotels from dataset
	BatchSize     int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"` // 0 means default batch size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartHotelSeedJobRequest) Reset() {
	*x = StartHotelSeedJobRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHotelSeedJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHotelSeedJobRequest) ProtoMessage() {}

func (x *StartHotelSeedJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHotelSeedJobRequest.ProtoReflect.Descriptor instead.
func (*StartHotelSeedJobRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{7}
}

func (x *StartHotelSeedJobRequest) GetClearExisting() bool {
	if x != nil {
		return x.ClearExisting
	}
	return false
}

func (x *StartHotelSeedJobRequest) GetMaxHotels() int32 {
	if x != nil {
		return x.MaxHotels
	}
	return 0
}

func (x *StartHotelSeedJobRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type GetHotelSeedJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelSeedJobStatusRequest) Reset() {
	*x = GetHotelSeedJobStatusRequest{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelSeedJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelSeedJobStatusRequest) ProtoMessage() {}

func (x *GetHotelSeedJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelSeedJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetHotelSeedJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{8}
}

func (x *GetHotelSeedJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ListHotelsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hotels        []*HotelInfo           `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHotelsReply) Reset() {
	*x = ListHotelsReply{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHotelsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotelsReply) ProtoMessage() {}

func (x *ListHotelsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotelsReply.ProtoReflect.Descriptor instead.
func (*ListHotelsReply) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{9}
}

func (x *ListHotelsReply) GetHotels() []*HotelInfo {
	if x != nil {
		return x.Hotels
	}
	return nil
}

func (x *ListHotelsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListHotelsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListHotelsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GenerateEmbeddingsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	JobId                string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status               string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EstimatedTimeSeconds int32                  `protobuf:"varint,3,opt,name=estimated_time_seconds,json=estimatedTimeSeconds,proto3" json:"estimated_time_seconds,omitempty"`
	TotalHotels          int32                  `protobuf:"varint,4,opt,name=total_hotels,json=totalHotels,proto3" json:"total_hotels,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GenerateEmbeddingsResponse) Reset() {
	*x = GenerateEmbeddingsResponse{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEmbeddingsResponse) ProtoMessage() {}

func (x *GenerateEmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*GenerateEmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateEmbeddingsResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GenerateEmbeddingsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateEmbeddingsResponse) GetEstimatedTimeSeconds() int32 {
	if x != nil {
		return x.EstimatedTimeSeconds
	}
	return 0
}

func (x *GenerateEmbeddingsResponse) GetTotalHotels() int32 {
	if x != nil {
		return x.TotalHotels
	}
	return 0
}

type GetEmbeddingStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	JobId               string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "running", "completed", "failed", "cancelled"
	Processed           int32                  `protobuf:"varint,3,opt,name=processed,proto3" json:"processed,omitempty"`
	Total               int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Progress            float32                `protobuf:"fixed32,5,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 to 1.0
	ErrorMessage        string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastUpdated         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	EstimatedCompletion *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetEmbeddingStatusResponse) Reset() {
	*x = GetEmbeddingStatusResponse{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbeddingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbeddingStatusResponse) ProtoMessage() {}

func (x *GetEmbeddingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbeddingStatusResponse.ProtoReflect.Descriptor instead.
func (*GetEmbeddingStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{11}
}

func (x *GetEmbeddingStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetEmbeddingStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetEmbeddingStatusResponse) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *GetEmbeddingStatusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetEmbeddingStatusResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetEmbeddingStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetEmbeddingStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetEmbeddingStatusResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *GetEmbeddingStatusResponse) GetEstimatedCompletion() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedCompletion
	}
	return nil
}

type StartHotelSeedJobResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	JobId                string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status               string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalHotels          int32                  `protobuf:"varint,3,opt,name=total_hotels,json=totalHotels,proto3" json:"total_hotels,omitempty"`
	EstimatedTimeSeconds int32                  `protobuf:"varint,4,opt,name=estimated_time_seconds,json=estimatedTimeSeconds,proto3" json:"estimated_time_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartHotelSeedJobResponse) Reset() {
	*x = StartHotelSeedJobResponse{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHotelSeedJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHotelSeedJobResponse) ProtoMessage() {}

func (x *StartHotelSeedJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHotelSeedJobResponse.ProtoReflect.Descriptor instead.
func (*StartHotelSeedJobResponse) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{12}
}

func (x *StartHotelSeedJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StartHotelSeedJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartHotelSeedJobResponse) GetTotalHotels() int32 {
	if x != nil {
		return x.TotalHotels
	}
	return 0
}

func (x *StartHotelSeedJobResponse) GetEstimatedTimeSeconds() int32 {
	if x != nil {
		return x.EstimatedTimeSeconds
	}
	return 0
}

type GetHotelSeedJobStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	JobId               string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "running", "completed", "failed", "cancelled"
	Processed           int32                  `protobuf:"varint,3,opt,name=processed,proto3" json:"processed,omitempty"`
	Total               int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Progress            float32                `protobuf:"fixed32,5,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 to 1.0
	Seeded              int32                  `protobuf:"varint,6,opt,name=seeded,proto3" json:"seeded,omitempty"`
	Skipped             int32                  `protobuf:"varint,7,opt,name=skipped,proto3" json:"skipped,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastUpdated         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	EstimatedCompletion *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetHotelSeedJobStatusResponse) Reset() {
	*x = GetHotelSeedJobStatusResponse{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelSeedJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelSeedJobStatusResponse) ProtoMessage() {}

func (x *GetHotelSeedJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelSeedJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetHotelSeedJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{13}
}

func (x *GetHotelSeedJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetHotelSeedJobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHotelSeedJobStatusResponse) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *GetHotelSeedJobStatusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetHotelSeedJobStatusResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetHotelSeedJobStatusResponse) GetSeeded() int32 {
	if x != nil {
		return x.Seeded
	}
	return 0
}

func (x *GetHotelSeedJobStatusResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *GetHotelSeedJobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetHotelSeedJobStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetHotelSeedJobStatusResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *GetHotelSeedJobStatusResponse) GetEstimatedCompletion() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedCompletion
	}
	return nil
}

type HotelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basic info
	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalId  string `protobuf:"bytes,2,opt,name=original_id,json=originalId,proto3" json:"original_id,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Brand       string `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Pricing
	ActualPrice        float64 `protobuf:"fixed64,6,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty"`
	SellingPrice       float64 `protobuf:"fixed64,7,opt,name=selling_price,json=sellingPrice,proto3" json:"selling_price,omitempty"`
	Discount           string  `protobuf:"bytes,8,opt,name=discount,proto3" json:"discount,omitempty"`
	PriceNumeric       int32   `protobuf:"varint,9,opt,name=price_numeric,json=priceNumeric,proto3" json:"price_numeric,omitempty"`
	DiscountPercentage float32 `protobuf:"fixed32,10,opt,name=discount_percentage,json=discountPercentage,proto3" json:"discount_percentage,omitempty"`
	// Categorization
	Category    string `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory string `protobuf:"bytes,12,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	// Stock & Seller
	OutOfStock bool   `protobuf:"varint,13,opt,name=out_of_stock,json=outOfStock,proto3" json:"out_of_stock,omitempty"`
	Seller     string `protobuf:"bytes,14,opt,name=seller,proto3" json:"seller,omitempty"`
	// Ratings
	AverageRating string  `protobuf:"bytes,15,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	RatingNumeric float32 `protobuf:"fixed32,16,opt,name=rating_numeric,json=ratingNumeric,proto3" json:"rating_numeric,omitempty"`
	// Media
	Images       []string `protobuf:"bytes,17,rep,name=images,proto3" json:"images,omitempty"`
	PrimaryImage string   `protobuf:"bytes,18,opt,name=primary_image,json=primaryImage,proto3" json:"primary_image,omitempty"`
	// Hotel details
	HotelDetails map[string]string `protobuf:"bytes,19,rep,name=hotel_details,json=hotelDetails,proto3" json:"hotel_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// URLs and identifiers
	Url       string `protobuf:"bytes,20,opt,name=url,proto3" json:"url,omitempty"`
	StyleCode string `protobuf:"bytes,22,opt,name=style_code,json=styleCode,proto3" json:"style_code,omitempty"`
	// Timestamps
	CrawledAt *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=crawled_at,json=crawledAt,proto3" json:"crawled_at,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Engagement metrics
	ViewCount     int32 `protobuf:"varint,26,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	ClickCount    int32 `protobuf:"varint,27,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	Featured      bool  `protobuf:"varint,28,opt,name=featured,proto3" json:"featured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotelInfo) Reset() {
	*x = HotelInfo{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelInfo) ProtoMessage() {}

func (x *HotelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelInfo.ProtoReflect.Descriptor instead.
func (*HotelInfo) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{14}
}

func (x *HotelInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HotelInfo) GetOriginalId() string {
	if x != nil {
		return x.OriginalId
	}
	return ""
}

func (x *HotelInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HotelInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *HotelInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HotelInfo) GetActualPrice() float64 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

func (x *HotelInfo) GetSellingPrice() float64 {
	if x != nil {
		return x.SellingPrice
	}
	return 0
}

func (x *HotelInfo) GetDiscount() string {
	if x != nil {
		return x.Discount
	}
	return ""
}

func (x *HotelInfo) GetPriceNumeric() int32 {
	if x != nil {
		return x.PriceNumeric
	}
	return 0
}

func (x *HotelInfo) GetDiscountPercentage() float32 {
	if x != nil {
		return x.DiscountPercentage
	}
	return 0
}

func (x *HotelInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *HotelInfo) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *HotelInfo) GetOutOfStock() bool {
	if x != nil {
		return x.OutOfStock
	}
	return false
}

func (x *HotelInfo) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *HotelInfo) GetAverageRating() string {
	if x != nil {
		return x.AverageRating
	}
	return ""
}

func (x *HotelInfo) GetRatingNumeric() float32 {
	if x != nil {
		return x.RatingNumeric
	}
	return 0
}

func (x *HotelInfo) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *HotelInfo) GetPrimaryImage() string {
	if x != nil {
		return x.PrimaryImage
	}
	return ""
}

func (x *HotelInfo) GetHotelDetails() map[string]string {
	if x != nil {
		return x.HotelDetails
	}
	return nil
}

func (x *HotelInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HotelInfo) GetStyleCode() string {
	if x != nil {
		return x.StyleCode
	}
	return ""
}

func (x *HotelInfo) GetCrawledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CrawledAt
	}
	return nil
}

func (x *HotelInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HotelInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *HotelInfo) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *HotelInfo) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *HotelInfo) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

type PriceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRange) Reset() {
	*x = PriceRange{}
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRange) ProtoMessage() {}

func (x *PriceRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_hotels_v1_hotels_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRange.ProtoReflect.Descriptor instead.
func (*PriceRange) Descriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_proto_rawDescGZIP(), []int{15}
}

func (x *PriceRange) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *PriceRange) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_api_hotels_v1_hotels_proto protoreflect.FileDescriptor

const file_api_hotels_v1_hotels_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/hotels/v1/hotels.proto\x12\fapi.hotel.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n" +
	"\x0fGetHotelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa5\x03\n" +
	"\x11ListHotelsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12!\n" +
	"\fsub_category\x18\x05 \x01(\tR\vsubCategory\x12\x1b\n" +
	"\tmin_price\x18\x06 \x01(\x05R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\a \x01(\x05R\bmaxPrice\x12\x1d\n" +
	"\n" +
	"min_rating\x18\b \x01(\x02R\tminRating\x12\x19\n" +
	"\bin_stock\x18\t \x01(\bR\ainStock\x12#\n" +
	"\rfeatured_only\x18\n" +
	" \x01(\bR\ffeaturedOnly\x12\x16\n" +
	"\x06seller\x18\v \x01(\tR\x06seller\x12\x17\n" +
	"\asort_by\x18\f \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\r \x01(\tR\tsortOrder\x12!\n" +
	"\fsearch_query\x18\x0e \x01(\tR\vsearchQuery\"\x98\x01\n" +
	"\x13SearchHotelsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x129\n" +
	"\vprice_range\x18\x04 \x01(\v2\x18.api.hotel.v1.PriceRangeR\n" +
	"priceRange\"L\n" +
	"\x18GetFeaturedHotelsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"?\n" +
	"\x17GetSimilarHotelsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"~\n" +
	"\x19GenerateEmbeddingsRequest\x12%\n" +
	"\x0eregenerate_all\x18\x01 \x01(\bR\rregenerateAll\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSize\x12\x1b\n" +
	"\thotel_ids\x18\x03 \x03(\x03R\bhotelIds\"2\n" +
	"\x19GetEmbeddingStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x7f\n" +
	"\x18StartHotelSeedJobRequest\x12%\n" +
	"\x0eclear_existing\x18\x01 \x01(\bR\rclearExisting\x12\x1d\n" +
	"\n" +
	"max_hotels\x18\x02 \x01(\x05R\tmaxHotels\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\"5\n" +
	"\x1cGetHotelSeedJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x89\x01\n" +
	"\x0fListHotelsReply\x12/\n" +
	"\x06hotels\x18\x01 \x03(\v2\x17.api.hotel.v1.HotelInfoR\x06hotels\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa4\x01\n" +
	"\x1aGenerateEmbeddingsResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x124\n" +
	"\x16estimated_time_seconds\x18\x03 \x01(\x05R\x14estimatedTimeSeconds\x12!\n" +
	"\ftotal_hotels\x18\x04 \x01(\x05R\vtotalHotels\"\x89\x03\n" +
	"\x1aGetEmbeddingStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tprocessed\x18\x03 \x01(\x05R\tprocessed\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x02R\bprogress\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\flast_updated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12M\n" +
	"\x14estimated_completion\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x13estimatedCompletion\"\xa3\x01\n" +
	"\x19StartHotelSeedJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\ftotal_hotels\x18\x03 \x01(\x05R\vtotalHotels\x124\n" +
	"\x16estimated_time_seconds\x18\x04 \x01(\x05R\x14estimatedTimeSeconds\"\xbe\x03\n" +
	"\x1dGetHotelSeedJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tprocessed\x18\x03 \x01(\x05R\tprocessed\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x02R\bprogress\x12\x16\n" +
	"\x06seeded\x18\x06 \x01(\x05R\x06seeded\x12\x18\n" +
	"\askipped\x18\a \x01(\x05R\askipped\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\flast_updated\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12M\n" +
	"\x14estimated_completion\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x13estimatedCompletion\"\x97\b\n" +
	"\tHotelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\voriginal_id\x18\x02 \x01(\tR\n" +
	"originalId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\factual_price\x18\x06 \x01(\x01R\vactualPrice\x12#\n" +
	"\rselling_price\x18\a \x01(\x01R\fsellingPrice\x12\x1a\n" +
	"\bdiscount\x18\b \x01(\tR\bdiscount\x12#\n" +
	"\rprice_numeric\x18\t \x01(\x05R\fpriceNumeric\x12/\n" +
	"\x13discount_percentage\x18\n" +
	" \x01(\x02R\x12discountPercentage\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\f \x01(\tR\vsubCategory\x12 \n" +
	"\fout_of_stock\x18\r \x01(\bR\n" +
	"outOfStock\x12\x16\n" +
	"\x06seller\x18\x0e \x01(\tR\x06seller\x12%\n" +
	"\x0eaverage_rating\x18\x0f \x01(\tR\raverageRating\x12%\n" +
	"\x0erating_numeric\x18\x10 \x01(\x02R\rratingNumeric\x12\x16\n" +
	"\x06images\x18\x11 \x03(\tR\x06images\x12#\n" +
	"\rprimary_image\x18\x12 \x01(\tR\fprimaryImage\x12N\n" +
	"\rhotel_details\x18\x13 \x03(\v2).api.hotel.v1.HotelInfo.HotelDetailsEntryR\fhotelDetails\x12\x10\n" +
	"\x03url\x18\x14 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"style_code\x18\x16 \x01(\tR\tstyleCode\x129\n" +
	"\n" +
	"crawled_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tcrawledAt\x129\n" +
	"\n" +
	"created_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"view_count\x18\x1a \x01(\x05R\tviewCount\x12\x1f\n" +
	"\vclick_count\x18\x1b \x01(\x05R\n" +
	"clickCount\x12\x1a\n" +
	"\bfeatured\x18\x1c \x01(\bR\bfeatured\x1a?\n" +
	"\x11HotelDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\n" +
	"PriceRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max2\xb6\x02\n" +
	"\x05Hotel\x12^\n" +
	"\bGetHotel\x12\x1d.api.hotel.v1.GetHotelRequest\x1a\x17.api.hotel.v1.HotelInfo\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/hotels/id/{id}\x12`\n" +
	"\n" +
	"ListHotels\x12\x1f.api.hotel.v1.ListHotelsRequest\x1a\x1d.api.hotel.v1.ListHotelsReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/hotels\x12k\n" +
	"\fSearchHotels\x12!.api.hotel.v1.SearchHotelsRequest\x1a\x1d.api.hotel.v1.ListHotelsReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/hotels/searchB2\n" +
	"\rapi.hotels.v1P\x01Z\x1ftrivgoo-backend/api/hotel/v1;v1b\x06proto3"

var (
	file_api_hotels_v1_hotels_proto_rawDescOnce sync.Once
	file_api_hotels_v1_hotels_proto_rawDescData []byte
)

func file_api_hotels_v1_hotels_proto_rawDescGZIP() []byte {
	file_api_hotels_v1_hotels_proto_rawDescOnce.Do(func() {
		file_api_hotels_v1_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_hotels_v1_hotels_proto_rawDesc), len(file_api_hotels_v1_hotels_proto_rawDesc)))
	})
	return file_api_hotels_v1_hotels_proto_rawDescData
}

var file_api_hotels_v1_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_hotels_v1_hotels_proto_goTypes = []any{
	(*GetHotelRequest)(nil),               // 0: api.hotel.v1.GetHotelRequest
	(*ListHotelsRequest)(nil),             // 1: api.hotel.v1.ListHotelsRequest
	(*SearchHotelsRequest)(nil),           // 2: api.hotel.v1.SearchHotelsRequest
	(*GetFeaturedHotelsRequest)(nil),      // 3: api.hotel.v1.GetFeaturedHotelsRequest
	(*GetSimilarHotelsRequest)(nil),       // 4: api.hotel.v1.GetSimilarHotelsRequest
	(*GenerateEmbeddingsRequest)(nil),     // 5: api.hotel.v1.GenerateEmbeddingsRequest
	(*GetEmbeddingStatusRequest)(nil),     // 6: api.hotel.v1.GetEmbeddingStatusRequest
	(*StartHotelSeedJobRequest)(nil),      // 7: api.hotel.v1.StartHotelSeedJobRequest
	(*GetHotelSeedJobStatusRequest)(nil),  // 8: api.hotel.v1.GetHotelSeedJobStatusRequest
	(*ListHotelsReply)(nil),               // 9: api.hotel.v1.ListHotelsReply
	(*GenerateEmbeddingsResponse)(nil),    // 10: api.hotel.v1.GenerateEmbeddingsResponse
	(*GetEmbeddingStatusResponse)(nil),    // 11: api.hotel.v1.GetEmbeddingStatusResponse
	(*StartHotelSeedJobResponse)(nil),     // 12: api.hotel.v1.StartHotelSeedJobResponse
	(*GetHotelSeedJobStatusResponse)(nil), // 13: api.hotel.v1.GetHotelSeedJobStatusResponse
	(*HotelInfo)(nil),                     // 14: api.hotel.v1.HotelInfo
	(*PriceRange)(nil),                    // 15: api.hotel.v1.PriceRange
	nil,                                   // 16: api.hotel.v1.HotelInfo.HotelDetailsEntry
	(*timestamppb.Timestamp)(nil),         // 17: google.protobuf.Timestamp
}
var file_api_hotels_v1_hotels_proto_depIdxs = []int32{
	15, // 0: api.hotel.v1.SearchHotelsRequest.price_range:type_name -> api.hotel.v1.PriceRange
	14, // 1: api.hotel.v1.ListHotelsReply.hotels:type_name -> api.hotel.v1.HotelInfo
	17, // 2: api.hotel.v1.GetEmbeddingStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	17, // 3: api.hotel.v1.GetEmbeddingStatusResponse.last_updated:type_name -> google.protobuf.Timestamp
	17, // 4: api.hotel.v1.GetEmbeddingStatusResponse.estimated_completion:type_name -> google.protobuf.Timestamp
	17, // 5: api.hotel.v1.GetHotelSeedJobStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	17, // 6: api.hotel.v1.GetHotelSeedJobStatusResponse.last_updated:type_name -> google.protobuf.Timestamp
	17, // 7: api.hotel.v1.GetHotelSeedJobStatusResponse.estimated_completion:type_name -> google.protobuf.Timestamp
	16, // 8: api.hotel.v1.HotelInfo.hotel_details:type_name -> api.hotel.v1.HotelInfo.HotelDetailsEntry
	17, // 9: api.hotel.v1.HotelInfo.crawled_at:type_name -> google.protobuf.Timestamp
	17, // 10: api.hotel.v1.HotelInfo.created_at:type_name -> google.protobuf.Timestamp
	17, // 11: api.hotel.v1.HotelInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 12: api.hotel.v1.Hotel.GetHotel:input_type -> api.hotel.v1.GetHotelRequest
	1,  // 13: api.hotel.v1.Hotel.ListHotels:input_type -> api.hotel.v1.ListHotelsRequest
	2,  // 14: api.hotel.v1.Hotel.SearchHotels:input_type -> api.hotel.v1.SearchHotelsRequest
	14, // 15: api.hotel.v1.Hotel.GetHotel:output_type -> api.hotel.v1.HotelInfo
	9,  // 16: api.hotel.v1.Hotel.ListHotels:output_type -> api.hotel.v1.ListHotelsReply
	9,  // 17: api.hotel.v1.Hotel.SearchHotels:output_type -> api.hotel.v1.ListHotelsReply
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_hotels_v1_hotels_proto_init() }
func file_api_hotels_v1_hotels_proto_init() {
	if File_api_hotels_v1_hotels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_hotels_v1_hotels_proto_rawDesc), len(file_api_hotels_v1_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hotels_v1_hotels_proto_goTypes,
		DependencyIndexes: file_api_hotels_v1_hotels_proto_depIdxs,
		MessageInfos:      file_api_hotels_v1_hotels_proto_msgTypes,
	}.Build()
	File_api_hotels_v1_hotels_proto = out.File
	file_api_hotels_v1_hotels_proto_goTypes = nil
	file_api_hotels_v1_hotels_proto_depIdxs = nil
}
