// api/hotel/v1/hotels_error_reason.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/hotels/v1/hotels_error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_HOTEL_UNSPECIFIED        ErrorReason = 0
	ErrorReason_HOTEL_NOT_FOUND          ErrorReason = 1
	ErrorReason_INVALID_HOTEL_ID         ErrorReason = 2
	ErrorReason_INVALID_PRICE_RANGE      ErrorReason = 3
	ErrorReason_INVALID_PARAMETERS       ErrorReason = 4
	ErrorReason_DATABASE_ERROR           ErrorReason = 5
	ErrorReason_SEARCH_FAILED            ErrorReason = 6
	ErrorReason_EMBEDDING_IS_NOT_ENABLED ErrorReason = 7
	ErrorReason_EMBEDDING_IS_NOT_FOUND   ErrorReason = 8
	// Admin embedding errors (9000-9999)
	ErrorReason_EMBEDDING_JOB_NOT_FOUND       ErrorReason = 9000
	ErrorReason_EMBEDDING_JOB_ALREADY_RUNNING ErrorReason = 9001
	ErrorReason_EMBEDDING_JOB_NOT_RUNNING     ErrorReason = 9002
	ErrorReason_EMBEDDING_GENERATION_FAILED   ErrorReason = 9003
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:    "HOTEL_UNSPECIFIED",
		1:    "HOTEL_NOT_FOUND",
		2:    "INVALID_HOTEL_ID",
		3:    "INVALID_PRICE_RANGE",
		4:    "INVALID_PARAMETERS",
		5:    "DATABASE_ERROR",
		6:    "SEARCH_FAILED",
		7:    "EMBEDDING_IS_NOT_ENABLED",
		8:    "EMBEDDING_IS_NOT_FOUND",
		9000: "EMBEDDING_JOB_NOT_FOUND",
		9001: "EMBEDDING_JOB_ALREADY_RUNNING",
		9002: "EMBEDDING_JOB_NOT_RUNNING",
		9003: "EMBEDDING_GENERATION_FAILED",
	}
	ErrorReason_value = map[string]int32{
		"HOTEL_UNSPECIFIED":             0,
		"HOTEL_NOT_FOUND":               1,
		"INVALID_HOTEL_ID":              2,
		"INVALID_PRICE_RANGE":           3,
		"INVALID_PARAMETERS":            4,
		"DATABASE_ERROR":                5,
		"SEARCH_FAILED":                 6,
		"EMBEDDING_IS_NOT_ENABLED":      7,
		"EMBEDDING_IS_NOT_FOUND":        8,
		"EMBEDDING_JOB_NOT_FOUND":       9000,
		"EMBEDDING_JOB_ALREADY_RUNNING": 9001,
		"EMBEDDING_JOB_NOT_RUNNING":     9002,
		"EMBEDDING_GENERATION_FAILED":   9003,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_hotels_v1_hotels_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_hotels_v1_hotels_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_hotels_v1_hotels_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_api_hotels_v1_hotels_error_reason_proto protoreflect.FileDescriptor

const file_api_hotels_v1_hotels_error_reason_proto_rawDesc = "" +
	"\n" +
	"'api/hotels/v1/hotels_error_reason.proto\x12\rapi.hotels.v1*\xe5\x02\n" +
	"\vErrorReason\x12\x15\n" +
	"\x11HOTEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHOTEL_NOT_FOUND\x10\x01\x12\x14\n" +
	"\x10INVALID_HOTEL_ID\x10\x02\x12\x17\n" +
	"\x13INVALID_PRICE_RANGE\x10\x03\x12\x16\n" +
	"\x12INVALID_PARAMETERS\x10\x04\x12\x12\n" +
	"\x0eDATABASE_ERROR\x10\x05\x12\x11\n" +
	"\rSEARCH_FAILED\x10\x06\x12\x1c\n" +
	"\x18EMBEDDING_IS_NOT_ENABLED\x10\a\x12\x1a\n" +
	"\x16EMBEDDING_IS_NOT_FOUND\x10\b\x12\x1c\n" +
	"\x17EMBEDDING_JOB_NOT_FOUND\x10\xa8F\x12\"\n" +
	"\x1dEMBEDDING_JOB_ALREADY_RUNNING\x10\xa9F\x12\x1e\n" +
	"\x19EMBEDDING_JOB_NOT_RUNNING\x10\xaaF\x12 \n" +
	"\x1bEMBEDDING_GENERATION_FAILED\x10\xabFB/\n" +
	"\fapi.hotel.v1P\x01Z\x1dyinni_backend/api/hotel/v1;v1b\x06proto3"

var (
	file_api_hotels_v1_hotels_error_reason_proto_rawDescOnce sync.Once
	file_api_hotels_v1_hotels_error_reason_proto_rawDescData []byte
)

func file_api_hotels_v1_hotels_error_reason_proto_rawDescGZIP() []byte {
	file_api_hotels_v1_hotels_error_reason_proto_rawDescOnce.Do(func() {
		file_api_hotels_v1_hotels_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_hotels_v1_hotels_error_reason_proto_rawDesc), len(file_api_hotels_v1_hotels_error_reason_proto_rawDesc)))
	})
	return file_api_hotels_v1_hotels_error_reason_proto_rawDescData
}

var file_api_hotels_v1_hotels_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_hotels_v1_hotels_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.hotels.v1.ErrorReason
}
var file_api_hotels_v1_hotels_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_hotels_v1_hotels_error_reason_proto_init() }
func file_api_hotels_v1_hotels_error_reason_proto_init() {
	if File_api_hotels_v1_hotels_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_hotels_v1_hotels_error_reason_proto_rawDesc), len(file_api_hotels_v1_hotels_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_hotels_v1_hotels_error_reason_proto_goTypes,
		DependencyIndexes: file_api_hotels_v1_hotels_error_reason_proto_depIdxs,
		EnumInfos:         file_api_hotels_v1_hotels_error_reason_proto_enumTypes,
	}.Build()
	File_api_hotels_v1_hotels_error_reason_proto = out.File
	file_api_hotels_v1_hotels_error_reason_proto_goTypes = nil
	file_api_hotels_v1_hotels_error_reason_proto_depIdxs = nil
}
