// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"yinni-travel-backend/app/booking/internal/biz"
	"yinni-travel-backend/app/booking/internal/data"
	"yinni-travel-backend/app/booking/internal/server"
	"yinni-travel-backend/app/booking/internal/service"
	"yinni-travel-backend/internal/conf"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, auth *conf.Auth, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	bookingRepo := data.NewBookingRepo(dataData, logger)
	bookingUsecase := biz.NewBookingUsecase(bookingRepo, logger)
	bookingService := service.NewBookingService(bookingUsecase)
	grpcServer := server.NewGRPCServer(confServer, bookingService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, bookingService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
